#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/2-infra-setup/storage-policies/openebs-sc node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

time="date"
current_time=$(eval $time)
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
# gittoken=$(echo "$github_token")

present_dir=$(pwd)
echo $present_dir

# echo "Setting up test dependencies.."
# ${utils_path}/setup_dependencies infra-setup

#pooling over previous job to complete
echo "***********Applying openebs-storage-clas********"
bash script/utils/pooling jobname:cstor-cspc-striped-pool
bash script/utils/e2e-cr jobname:policies jobphase:Waiting
bash script/utils/e2e-cr jobname:policies jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=cstor-storage-policies metadata="")
echo $test_name

git clone https://github.com/openebs/cstor-operators.git
cd cstor-operators/e2e-tests

kubectl apply -f hack/rbac.yaml
kubectl apply -f hack/crds.yaml

cp experiments/cstor-operator/cstor-storage-policies/run_e2e_test.yml cstor-csi-sc.yaml

cat cstor-csi-sc.yaml

bash ../../script/utils/e2e_job_runner label='app:cstor-storage-policy' job=cstor-csi-sc.yaml

echo "Dumping state of cluster post job run"; echo ""
bash ../../script/utils/dump_cluster_state;

cd ../..
bash script/utils/event_updater jobname:s2-j3-policies $test_name jobid:"$job_id" pipelineid:"$pipeline_id" 
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
# source ~/.profile
# gittoken=$(echo "$github_token")
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:policies jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass 

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi