#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone -b release-branch https://github.com/mayadata-io/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/2-setup/K9YC-openebs-deploy/deploy-openebs node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$RELEASE_BRANCH'"' '"'$E_USER'"' '"'$E_PASSWORD'"' '"'$OPENEBS_MAYA_APISERVER_IMAGE'"' '"'$OPENEBS_PROVISIONER_IMAGE'"' '"'$OPENEBS_SNAPSHOT_CONTROLLER_IMAGE'"' '"'$OPENEBS_SNAPSHOT_PROVISIONER_IMAGE'"' '"'$OPENEBS_IO_JIVA_IMAGE'"' '"'$OPENEBS_MAYA_EXPORTER_IMAGE'"' '"'$OPENEBS_NODE_DISK_MANAGER_IMAGE'"' '"'$OPENEBS_NODE_DISK_OPERATOR_IMAGE'"' '"'$OPENEBS_IO_CSTOR_TARGET_IMAGE'"' '"'$OPENEBS_IO_CSTOR_POOL_IMAGE'"' '"'$OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE'"' '"'$OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE'"' '"'$OPENEBS_LOCALPV_PROVISIONER_IMAGE'"' '"'$OPENEBS_ADMISSION_SERVER_IMAGE'"' '"'$OPENEBS_CLEANUP_JOB_IMAGE'"' '"'$DEPLOY_MODE'"' '"'$HELM_REPO'"' '"'$HELM_BRANCH'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
releaseBranch=$(echo $5)
case_id=K9YC
elastic_user=$(echo $6)
elastic_password=$(echo $7)
maya_api_server_image=$(echo $8)
provisioner_image=$(echo $9)
snapshot_controller_image=$(echo ${10})
snapshot_provisioner_image=$(echo ${11})
jiva_image=$(echo ${12})
maya_exporter_image=$(echo ${13})
ndm_image=$(echo ${14})
ndm_operator_image=$(echo ${15})
cstor_target_image=$(echo ${16})
cstor_pool_image=$(echo ${17})
cstor_pool_mgmt_image=$(echo ${18})
cstor_volume_mgmt_image=$(echo ${19})
localpv_provisioner_image=$(echo ${20})
admission_server_image=$(echo ${21})
cleanup_job_image=$(echo ${22})
deploy_mode=$(echo ${23})
helm_repo=$(echo ${24})
helm_branch=$(echo ${25})

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

echo "releaseTag=$releaseTag"

for i in efk-vars.yml efk.yml get_url.yml; do
  wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/workload/efk-client/playbook/$i
done

echo "EFK: Deploying Aggregrator and Forwarder on client"
ansible-playbook efk.yml --extra-vars "commit_id=$commit_id pipeline_id=$pipeline_id e_user=$elastic_user e_password=$elastic_password" 

# Applying e2e-CRD
echo "***Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "*****Deploying openebs*******"
bash Openshift-EE/utils/e2e-cr jobname:s2-j1-openebs-deploy jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:s2-j1-openebs-deploy jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash Openshift-EE/utils/e2e-cr jobname:cstor-integration-test jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-jiva-volume jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-negative-invalid-storage-pool-claim jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-jiva-node-stickiness jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-jiva-snapshot jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-jiva-clone jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-volume-clone-provisioning jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-snapshot-provisioning jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-volume-provisioning jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-volume-provision-waitforfirstconsumer jobphase:Waiting
# bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-volume-provisioning-negative jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:bdd-cstor-scaleup-replica jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:s2-j6-policies jobphase:Waiting 
bash Openshift-EE/utils/e2e-cr jobname:s2-j2-cstor-striped-pool jobphase:Waiting 
bash Openshift-EE/utils/e2e-cr jobname:s2-j3-cstor-mirrored-pool jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:s2-j4-cstor-raidz1-pool jobphase:Waiting
# bash Openshift-EE/utils/e2e-cr jobname:s2-j5-cstor-raidz2-pool jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:s2-j7-nfsv4-provision jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:s2-j8-nfsv4-jiva-provision jobphase:Waiting

source ~/.profile


echo "Generating test name***************************"
test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-provision metadata="")
echo $test_name

## Clone the litmus repo, navigate to litmus root 

git clone https://github.com/mayadata-io/litmus.git
cd litmus

sed -i -e '/name: OPENEBS_MAYA_APISERVER_IMAGE/{n;s/.*/            value: '"'$maya_api_server_image'"'/}' \
-e '/name: OPENEBS_PROVISIONER_IMAGE/{n;s/.*/            value: '"'$provisioner_image'"'/}' \
-e '/name: OPENEBS_SNAPSHOT_CONTROLLER_IMAGE/{n;s/.*/            value: '"'$snapshot_controller_image'"'/}' \
-e '/name: OPENEBS_SNAPSHOT_PROVISIONER_IMAGE/{n;s/.*/            value: '"'$snapshot_provisioner_image'"'/}' \
-e '/name: OPENEBS_IO_JIVA_IMAGE/{n;s/.*/            value: '"'$jiva_image'"'/}' \
-e '/name: OPENEBS_MAYA_EXPORTER_IMAGE/{n;s/.*/            value: '"'$maya_exporter_image'"'/}' \
-e '/name: OPENEBS_NODE_DISK_MANAGER_IMAGE/{n;s/.*/            value: '"'$ndm_image'"'/}' \
-e '/name: OPENEBS_NODE_DISK_OPERATOR_IMAGE/{n;s/.*/            value: '"'$ndm_operator_image'"'/}' \
-e '/name: OPENEBS_IO_CSTOR_TARGET_IMAGE/{n;s/.*/            value: '"'$cstor_target_image'"'/}' \
-e '/name: OPENEBS_IO_CSTOR_POOL_IMAGE/{n;s/.*/            value: '"'$cstor_pool_image'"'/}' \
-e '/name: OPENEBS_IO_CSTOR_POOL_MGMT_IMAGE/{n;s/.*/            value: '"'$cstor_pool_mgmt_image'"'/}' \
-e '/name: OPENEBS_IO_CSTOR_VOLUME_MGMT_IMAGE/{n;s/.*/            value: '"'$cstor_volume_mgmt_image'"'/}' \
-e '/name: OPENEBS_LOCALPV_PROVISIONER_IMAGE/{n;s/.*/            value: '"'$localpv_provisioner_image'"'/}' \
-e '/name: OPENEBS_ADMISSION_SERVER_IMAGE/{n;s/.*/            value: '"'$admission_server_image'"'/}' \
-e '/name: OPENEBS_CLEANUP_JOB_IMAGE/{n;s/.*/            value: '"'$cleanup_job_image'"'/}' \
-e '/name: DEPLOY_MODE/{n;s/.*/            value: '"'$deploy_mode'"'/}' \
-e '/name: HELM_REPO/{n;s/.*/            value: '"'$helm_repo'"'/}' \
-e '/name: HELM_BRANCH/{n;s/.*/            value: '"'$helm_branch'"'/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yml

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e "s/value: '10'/value: '20'/g" \
-e "s/value: master/value: $releaseBranch/g" providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yml

cat providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yml

#################
## RUNNER MAIN ##
#################

echo "Applying rbac.yml********************************"
kubectl apply -f ./hack/rbac.yaml
kubectl apply -f ./hack/crds.yaml

echo "Copying kube config for litmus"
cp ~/.kube/config admin.conf
kubectl create cm kubeconfig --from-file=admin.conf -n litmus

echo "Running litmus test for openebs deploy.."

run_test=providers/openebs/installers/operator/master/litmusbook/run_litmus_test.yml
bash ../Openshift-EE/utils/litmus_job_runner label='provider:openebs-runner' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
bash ../Openshift-EE/utils/dump_cluster_state;
cd ..
bash Openshift-EE/utils/event_updater jobname:s2-j1-openebs-deploy $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)
test_case_id="K9YC"

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
#python3 Openshift-EE/utils/result/result_update.py $job_id K9YC 2-setup "Deploy OpenEBS in OpenShift-EE-3.10 Cluster" $testResult $pipeline_id "$current_time" $commit_id $gittoken

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:s2-j1-openebs-deploy jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 Openshift-EE/utils/result/result_update.py $job_id K9YC 2-setup "Deploy OpenEBS in OpenShift-EE Cluster" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11} ${12} ${13} ${14} ${15} ${16} ${17} ${18} ${19} ${20} ${21} ${22} ${23} ${24} ${25} ${26}
else
  pod
fi
