#!/bin/bash

pod() {
### Taint the node to run infra chaos test scripts

node_name=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes --no-headers | grep -v master | awk 'FNR==1 {print $1}')
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port "kubectl taint nodes $node_name infra-aid=observer:NoSchedule"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port "mkdir infra && echo $node_name >> infra/node_name"

echo $node_name
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/5-infra-chaos/5ICJO01-node-failure node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$node_name'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=5ICJO01
observer_node=$4

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
bash openebs-openshift-e2e/utils/e2e-cr jobname:node-failure-csi-jiva jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:containerd-failure-csi-jiva jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:node-failure-csi-jiva jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

echo "*******Deploying Busybox-Deployment****"

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-node-failure-csi-jiva metadata="")
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for Busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml app_deploy_csi_node_failure.yml

sed -i -e 's/app-busybox-ns/node-failure-csi-jiva/g' \
-e 's/busybox-e2e/node-failure-csi-jiva/g' \
-e 's/app=busybox/app=node-failure-csi-jiva/g' \
-e 's/openebs-jiva-csi/jiva-csi-sc/g' app_deploy_csi_node_failure.yml

cat app_deploy_csi_node_failure.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:node-failure-csi-jiva' app_deploy_csi_node_failure.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:node-failure-csi-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Fail "$current_time" $gittoken
exit 1;
fi

################
# e2eBook 2 #
################

run_id="node-failure-csi-jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_node_failure_csi_jiva.yml

# Update the environmental variables in e2e job spec.

sed -i -e 's/value: app-busybox-ns/value: node-failure-csi-jiva/g' \
-e 's/app=busybox/app=node-failure-csi-jiva/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-node-failure-csi-jiva/g' busybox_loadgen_node_failure_csi_jiva.yml

cat busybox_loadgen_node_failure_csi_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_node_failure_csi_jiva.yml

# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-node-failure-csi-jiva' job=busybox_loadgen_node_failure_csi_jiva.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-openshift-e2e/utils/event_updater jobname:node-failure-csi-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Fail "$current_time" $gittoken
exit 1;
fi

################
# e2eBook 3 #
################

run_id="csi-jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=node-failure metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
cp experiments/infra-chaos/jiva_node_failure/run_e2e_test.yml run_node_failure_csi.yml

sed -i -e 's/password:/password: cGFzc3dvcmQ=/g' \
-e 's/name: node-password/name: node-password-node-failure/g' \
-e 's/passwordNode:/passwordNode: UmFuZG9t/g' run_node_failure_csi.yml

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: node-failure-csi-jiva/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=node-failure-csi-jiva'\''/}' \
-e '/name: APP_PVC/{n;s/.*/            value: openebs-busybox/}' run_node_failure_csi.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_node_failure_csi.yml

sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_node_failure_csi.yml

sed -i '/name: ESX_HOST_IP/{n;s/.*/            value: 10.43.1.1/}' run_node_failure_csi.yml

sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: nodefailure
' run_node_failure_csi.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_node_failure_csi.yml

cat run_node_failure_csi.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='name:jiva-node-failure' run_node_failure_csi.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:node-failure-csi-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Fail "$current_time" $gittoken
exit 1;
fi

################
# e2eBook 4 #
################

run_id="deprovision-node-failure-csi-jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_deprovision_node_failure_csi.yml

# Update the environmental variables in e2e job spec.

sed -i -e 's/value: app-busybox-ns/value: node-failure-csi-jiva/g' \
-e 's/app=busybox/app=node-failure-csi-jiva/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: e2e-busybox-liveness/generateName: busybox-liveness-dep-node-failure-csi/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-deprovision-node-failure-csi/g' busybox_loadgen_deprovision_node_failure_csi.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_node_failure_csi.yml

cat busybox_loadgen_deprovision_node_failure_csi.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-deprovision-node-failure-csi' job=busybox_loadgen_deprovision_node_failure_csi.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:node-failure-csi-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Fail "$current_time" $gittoken
exit 1;
fi

################
# e2eBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-node-failure-csi-jiva metadata="")
echo $test_name

cd jiva-operator/e2e-tests
cp apps/busybox/deployers/run_e2e_test.yml deprovision_node_failure_csi.yml

sed -i -e 's/generateName: e2e-busybox-deploy/generateName: e2e-busybox-deprovision-csi/g' \
-e 's/app-busybox-ns/node-failure-csi-jiva/g' \
-e 's/app=busybox/app=node-failure-csi-jiva/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/busybox-e2e/busybox-deprovision-node-failure-csi/g' \
-e 's/openebs-jiva-csi/jiva-csi-sc/g' \
-e 's/value: provision/value: deprovision/g' deprovision_node_failure_csi.yml

cat deprovision_node_failure_csi.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-deprovision-node-failure-csi' deprovision_node_failure_csi.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:node-failure-csi-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:node-failure-csi-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Fail "$current_time" $gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:node-failure-csi-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 5ICJO01 5-infra-chaos "Fail the node where the application is running and check the behaviour" Pass "$current_time" $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
