#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/9-csi-chaos/LJIJ-cspc-cstor-pool-kill/cspc-cstor-pool-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=LJIJ

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
bash Openshift-EE/utils/e2e-cr jobname:cspc-cstor-pool-kill jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:cspc-cstor-pool-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-cstor-pool-kill metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_cstor_pool_kill.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-cstor-pool-kill/g' \
-e 's/app=busybox-sts/app=cstor-pool-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-csi/g' \
-e 's/value: openebs-busybox/value: openebs-bb-poolkill/g' \
-e 's/value: app-busybox-ns/value: cstor-pool-kill/g' busybox_cstor_pool_kill.yml
cat busybox_cstor_pool_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-cstor-pool-kill' job=busybox_cstor_pool_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cspc-cstor-pool-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on CSPC cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="cstor-pool-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_cstor_pool_kill.yml

sed -i -e 's/value: app-busybox-ns/value: cstor-pool-kill/g' \
-e 's/app=busybox-sts/app=cstor-pool-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-cstor-pool-kill/g' busybox_loadgen_cstor_pool_kill.yml

cat busybox_loadgen_cstor_pool_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_cstor_pool_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-cstor-pool-kill' job=busybox_loadgen_cstor_pool_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:cspc-cstor-pool-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on CSPC cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

echo "*******Performing CSPC cStor Pool kill**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=cspc-pool-failure metadata="")
echo $test_name

cd litmus
cp experiments/chaos/cspc_pool_failure/container_failure/run_litmus_test.yml cspc-poolkill.yml

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: cstor-pool-kill/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=cstor-pool-kill/g}' \
-e '/name: APP_PVC/{n;s/.*/            value: openebs-bb-poolkill/g}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' cspc-poolkill.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: cspcpoolkill
' cspc-poolkill.yml

echo "Running the litmus test for Busybox Deployment application pod kill.."
cat cspc-poolkill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:cspc-pool-failure' job=cspc-poolkill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cspc-cstor-pool-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-cstor-pool-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_cstor_pool_kill.yml

# Update the environmental variables in litmus job spec.

sed -i -e 's/value: app-busybox-ns/value: cstor-pool-kill/g' \
-e 's/app=busybox-sts/app=cstor-pool-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-cstor-pool-kill/g' busybox_loadgen_deprovision_cstor_pool_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_cstor_pool_kill.yml

cat busybox_loadgen_deprovision_cstor_pool_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-cstor-pool-kill' job=busybox_loadgen_deprovision_cstor_pool_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cspc-cstor-pool-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-cstor-pool-kill metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_cstor_pool_kill.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-cstor-pool-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-cstor-pool-kill/g' \
-e 's/app=busybox-sts/app=cstor-pool-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-poolkill/g' \
-e 's/value: app-busybox-ns/value: cstor-pool-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_cstor_pool_kill.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_cstor_pool_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-cstor-pool-kill' job=deprovision_cstor_pool_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cspc-cstor-pool-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:cspc-cstor-pool-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:cspc-cstor-pool-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id LJIJ 9-csi-chaos "Induce failure on cStor pool container(cstor-pool) and check if it is recovered successfully and verify that the application is not impacted" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
