#!/bin/bash
set -x

pod() {
### Tainting the node to run infra chaos test scripts
echo "******* Tainting node ********"
node_name=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes | grep worker | awk 'FNR==1 {print $1}')
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port "kubectl taint nodes $node_name infra-aid=observer:NoSchedule"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port "mkdir infra && echo $node_name >> infra/node_name"

sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/5-infra-chaos/BF12-taint-node/node-taint node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$node_name'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=BF12
observer_node=$4
releaseTag=$(echo $5)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:taint-node jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:drain-node jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:fill-node-capacity jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:node-failure-cstor jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:node-failure-jiva jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:taint-node jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox-Deployment****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-taint-node metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml deploy_evict_test.yml

: << EOF
  -------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                             |
  -------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | taint-node                                     |
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-evict                             |
 | appLabel          | env    | app=busybox-sts                     | app=taint-node                                 | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                             |
 | deploy type       | env    | statefulset                         | deployment                                     |
  --------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app-busybox-ns/taint-node/g' \
-e 's/busybox-litmus/busybox-evict/g' \
-e 's/app=busybox-sts/app=taint-node/g' \
-e 's/openebs-cstor-sparse/openebs-cstor-disk/g' \
-e 's/statefulset/deployment/g' deploy_evict_test.yml

cat deploy_evict_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-evict' deploy_evict_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:taint-node $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="taint-node";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_taint_node.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | taint-node                                       | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-taintnode             |
 | appLabel          | env    | app=busybox-sts                     | app=taint-node                                   | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: taint-node/g' \
-e 's/app=busybox-sts/app=taint-node/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-taintnode/g' busybox_loadgen_taint_node.yml

cat busybox_loadgen_taint_node.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_taint_node.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-taintnode' job=busybox_loadgen_taint_node.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:taint-node $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

echo "******TAINT NODE**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=node-failure-taint metadata="")
echo $test_name

cd litmus
cp experiments/chaos/taint_node/run_litmus_test.yml run_evict_test.yml

sed -i -e 's/value: app-percona-ns/value: taint-node/g' \
-e 's/name=percona/app=taint-node/g' \
-e 's/value: "enable"/value:/g' \
-e 's/liveness=percona-liveness/liveness=/g' run_evict_test.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_evict_test.yml

cat run_evict_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:node-failure-taint' run_evict_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:taint-node $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-taint-node";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_taint_node.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | taint-node                                       | 
 | appLabel          | env    | app=busybox-sts                     | app=taint-node                                   |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-taintnode |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: taint-node/g' \
-e 's/app=busybox-sts/app=taint-node/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-taintnode/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-taintnode/g' busybox_loadgen_deprovision_taint_node.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_taint_node.yml

cat busybox_loadgen_deprovision_taint_node.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-taintnode' job=busybox_loadgen_deprovision_taint_node.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:taint-node $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-taint-node metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_evict_node.yml

: << EOF
  -------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                             |
  -------------------------------------------------------------------------------------------------------------------|
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName:litmus-busybox-deprovision        |
 | appNamespace      | env    | app-busybox-ns                      | taint-node                                     |
 | appLabel          | env    | app=busybox-sts                     | app=taint-node                                 |
 | deploy type       | env    | statefulset                         | deployment                                     |
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-evict                 | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                             |
 | Action            | env    | provision                           | deprovision                                    |
  --------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: litmus-busybox-deprovision/g' \
-e 's/app-busybox-ns/taint-node/g' \
-e 's/app=busybox-sts/app=taint-node/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/busybox-litmus/busybox-deprovision-evict/g' \
-e 's/openebs-cstor-sparse/openebs-cstor-disk/g' \
-e 's/value: provision/value: deprovision/g' deprovision_evict_node.yml

cat deprovision_evict_node.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-evict' deprovision_evict_node.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:taint-node $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:taint-node jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:taint-node jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id BF12 5-infra-chaos "Taint the node where the application is running and check the behaviour" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
