#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/4-upgrade-openebs/upgrade-cstor-operator node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$FROM_VERSION'"' '"'$RELEASE_TAG'"' '"'$TO_VERSION'"' '"'$CSI_UPGRADE_IMAGE_TAG'"' '"'$COMMIT_ID'"' '"'$RC_TAG'"'
}


node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
from_version=$(echo $5)
releasebranch=$(echo $6)
to_version=$(echo $7)
csi_upgrade_imageTag=$(echo $8)
release_commit_id=$(echo $9)
rc_tag=$(echo ${10})

source ~/.profile

present_dir=$(pwd)
echo $present_dir

# echo "Setting up test dependencies.."	
# ${utils_path}/setup_dependencies e2e-test

bash script/utils/e2e-cr jobname:upgrade-cstor-operator jobphase:Waiting
bash script/utils/e2e-cr jobname:upgrade-cstor-operator jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

test_name=$(bash script/utils/generate_test_name testcase=cstor-csi-upgrade metadata="")
echo $test_name

git clone https://github.com/openebs/upgrade.git
cd  upgrade/e2e-tests

kubectl apply -f hack/rbac.yaml
kubectl apply -f hack/crds.yaml

cp experiments/cspc_csi_upgrade/run_e2e_test.yml upgrade-cstor-operator.yml

sed -i -e '/name: CSTOR_OPERATOR_UPGRADE/{n;s/.*/            value: "true"/}' \
-e '/name: FROM_VERSION/{n;s/.*/            value: '"'$from_version'"'/}' \
-e '/name: TO_VERSION/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: COMMIT_ID/{n;s/.*/            value: '"'$release_commit_id'"'/}' \
-e '/name: RELEASE_VERSION/{n;s/.*/            value: '"'$releasebranch'"'/}' \
-e '/name: RC_TAG/{n;s/.*/            value: '"'$rc_tag'"'/}' \
-e '/name: UPGRADE_IMAGE_TAG/{n;s/.*/            value: '"'$csi_upgrade_imageTag'"'/}' upgrade-cstor-operator.yml

sed -i -e 's/app: cstor-csi-upgrade/app: cstor-csi-operator-upgrade/g' upgrade-cstor-operator.yml

cat upgrade-cstor-operator.yml

bash ../../script/utils/e2e_job_runner label='app:cstor-csi-operator-upgrade' job=upgrade-cstor-operator.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../../script/utils/dump_cluster_state;

cd ../..
bash script/utils/event_updater jobname:upgrade-cstor-operator $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash script/utils/e2e-cr jobname:upgrade-cstor-operator jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}
else
  pod
fi
