#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/3-functional/percona-deployment-cstor/percona-deployment-cstor node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

# echo "Setting up test dependencies.."	
# ${utils_path}/setup_dependencies e2e-test

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-deployment-cstor jobphase:Waiting
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-deployment-cstor jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

##Deploying percona Application

run_id="cstor";test_name=$(bash openebs-openshift-e2e/script/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

git clone https://github.com/openebs/cstor-operators.git
cd  cstor-operators/e2e-tests

kubectl apply -f hack/rbac.yaml
kubectl apply -f hack/crds.yaml

echo "Running the e2e test for percona Deployment..."
cp apps/percona/deployers/run_e2e_test.yml deploy_percona_cstor.yml

sed -i -e 's/value: app-percona-ns/value: percona-cstor/g' \
-e 's/generateName: e2e-percona-/generateName: e2e-percona-cstor-/g' \
-e 's/app: percona-deployment/app: percona-deployment-cstor/g' deploy_percona_cstor.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_percona_cstor.yml

sed -i '/name: TARGET_AFFINITY_CHECK/{n;s/.*/            value: /g}' deploy_percona_cstor.yml

cat deploy_percona_cstor.yml

bash ../../openebs-openshift-e2e/script/utils/e2e_job_runner label='app:percona-deployment-cstor' job=deploy_percona_cstor.yml
cd ../..

bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:percona-deployment-cstor $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##Loadgen on percona Application

run_id="cstor";test_name=$(bash openebs-openshift-e2e/script/utils/generate_test_name testcase=percona-loadgen metadata=${run_id})
echo $test_name

cd  cstor-operators/e2e-tests
echo "Running the e2e test for Loadgen for percona Application..."
cp apps/percona/workload/run_e2e_test.yml loadgen_percona_cstor.yml

sed -i -e 's/generateName: percona-loadgen-/generateName: percona-cstor-loadgen-/g' \
-e 's/value: app-percona-ns/value: percona-cstor/g' \
-e 's/loadgen: percona-loadjob/loadgen: percona-cstor-loadjob/g' loadgen_percona_cstor.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_percona_cstor.yml

cat loadgen_percona_cstor.yml

bash ../../openebs-openshift-e2e/script/utils/e2e_job_runner label='loadgen:percona-cstor-loadjob' job=loadgen_percona_cstor.yml
cd ../..

bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:percona-deployment-cstor $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-deployment-cstor jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-deployment-cstor jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass


if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi