#!/bin/bash
set -x


pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/GFL0-target-network-delay/target-network-delay node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo $job_id
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > target-network-delay-result.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/target-network-delay/g" -e"s/<job_id>/$job_id/g" target-network-delay-result.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" target-network-delay-result.yml
kubectl apply -f target-network-delay-result.yml
cat target-network-delay-result.yml

echo "*******Deploying Application****"
sleep 5
echo "      Application-Deployment: Pass" >> target-network-delay-result.yml
cat target-network-delay-result.yml
kubectl apply -f target-network-delay-result.yml

echo "*******Generating load**********"
sleep 5
echo "      Application-Loadgen: Pass" >> target-network-delay-result.yml
cat target-network-delay-result.yml
kubectl apply -f target-network-delay-result.yml

echo "*******Inducing target-network-delay************"
sleep 5
echo "      target-network-delay: Fail" >> target-network-delay-result.yml
cat target-network-delay-result.yml
kubectl apply -f target-network-delay-result.yml

echo "*******Deprovisioning Application******"
sleep 5
echo "      Application-Deprovisioning: Pass" >> target-network-delay-result.yml
cat target-network-delay-result.yml
kubectl apply -f target-network-delay-result.yml

current_time=$(eval $time)
sed -i -e "s/<test-finish>/$current_time/g" target-network-delay-result.yml
sed -i -e "s/<test-result>/Fail/g" target-network-delay-result.yml
cat target-network-delay-result.yml
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
