#!/bin/bash

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FCO14-block-pool-deletion-with-volume node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
#gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=3FCO14

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-openshift-e2e/utils/e2e-cr jobname:block-pool-deletion-with-volume jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:block-pool-deletion-with-volume jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

run_id="csi-volume";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-busybox-csi-volume metadata=${run_id})
echo $test_name
oc adm policy add-scc-to-user anyuid system:serviceaccount:busybox-csi-volume:default

cd cstor-operators/e2e-tests
echo "Running the e2e test for busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml deploy_csi_busybox_volume.yml

sed -i -e 's/value: app-busybox-ns/value: busybox-csi-volume/g' \
-e 's/app: busybox-e2e/app: busybox-e2e-csi-volume/g' \
-e 's/generateName: e2e-busybox-deploy-/generateName: e2e-busybox-csi-/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi/g' deploy_csi_busybox_volume.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_csi_busybox_volume.yml

cat deploy_csi_busybox_volume.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-e2e-csi-volume' job=deploy_csi_busybox_volume.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:block-pool-deletion-with-volume $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

################
# e2eBook 1 #
################

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=block-cspc-pool-deletion-if-pool-with-volume metadata='')
echo $test_name

cd cstor-operators/e2e-tests

cp experiments/functional/cspc-pool/block-pool-deletion-with-volume/run_e2e_test.yml block-pool-deletion-with-volume.yml

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: busybox-csi-volume/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=busybox/g}' block-pool-deletion-with-volume.yml

cat block-pool-deletion-with-volume.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:pool-deletion-with-volume' job=block-pool-deletion-with-volume.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:block-pool-deletion-with-volume $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:block-pool-deletion-with-volume jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO14 3-functional "Verify if the pool creation is failed when the blockdevice is already claimed" Fail "$current_time" $#gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:block-pool-deletion-with-volume jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
