#!/bin/bash

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FCO06-csi-volume-scaledown node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
#gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=3FCO06

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-scaledown jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-scaledown jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

echo "****Deploying busybox Application using CSI volume with single replica****"

oc adm policy add-scc-to-user anyuid system:serviceaccount:csi-vol-scaledown:default

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-csi-vol-scaledown metadata='')
echo $test_name

cd cstor-operators/e2e-tests
echo "Running the e2e test for busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml busybox_csi_vol_scaledown.yml

sed -i -e 's/value: app-busybox-ns/value: csi-vol-scaledown/g' \
-e 's/app: busybox-e2e/app: busybox-e2e-csi-vol-scaledown/g' \
-e 's/generateName: e2e-busybox-deploy-/generateName: e2e-busybox-csi-vol-scaledown-/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi/g' busybox_csi_vol_scaledown.yml

cat busybox_csi_vol_scaledown.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-e2e-csi-vol-scaledown' job=busybox_csi_vol_scaledown.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-scaledown $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Scaling down the cstor csi volume replica" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 2 #
################

echo "****Busybox liveness****"

run_id="csi-vol-scaledown";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd cstor-operators/e2e-tests
echo "Running the e2e test for busybox liveness..."
cp apps/busybox/liveness/run_e2e_test.yml liveness_csi_vol_scaledown.yml

sed -i -e 's/liveness: e2e-busybox-liveness/liveness: e2e-busybox-csi-vol-scaledown/g' \
-e 's/generateName: e2e-busybox-liveness-/generateName: e2e-busybox-liveness-csi-vol-scaledown-/g' \
-e 's/value: app-busybox-ns/value: csi-vol-scaledown/g' liveness_csi_vol_scaledown.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' liveness_csi_vol_scaledown.yml

cat liveness_csi_vol_scaledown.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:e2e-busybox-csi-vol-scaledown' job=liveness_csi_vol_scaledown.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-scaledown $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Liveness on application and verify the status" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 3 #
################

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=cstor-csi-replica-scaledown metadata='')
echo $test_name

cd cstor-operators/e2e-tests
cp experiments/functional/cstor-csi-volume-scaledown/run_e2e_test.yml run_cstor_csi_vol_scaledown.yml

sed -i -e '/name: APP_PVC/{n;s/.*/            value: openebs-busybox/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=busybox/g}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/g}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: csi-vol-scaledown/g}' run_cstor_csi_vol_scaledown.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: scaledown
' run_cstor_csi_vol_scaledown.yml

cat run_cstor_csi_vol_scaledown.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='name:cstor-csi-replica-scaledown' job=run_cstor_csi_vol_scaledown.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-scaledown $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Check if the csi volume replica is scaled down" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 4 #
################

echo "****Busybox liveness deprovision****"

run_id="deprovision-csi-vol-scaledown";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd cstor-operators/e2e-tests
echo "Running the e2e test for busybox liveness..."
cp apps/busybox/liveness/run_e2e_test.yml dep_liveness_csi_vol_scaledown.yml

sed -i -e 's/liveness: e2e-busybox-liveness/liveness: e2e-busybox-dep-csi-vol-scaledown/g' \
-e 's/generateName: e2e-busybox-liveness-/generateName: e2e-busybox-liveness-dep-csi-vol-scaledown-/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-busybox-ns/value: csi-vol-scaledown/g' dep_liveness_csi_vol_scaledown.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' dep_liveness_csi_vol_scaledown.yml

cat dep_liveness_csi_vol_scaledown.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:e2e-busybox-dep-csi-vol-scaledown' job=dep_liveness_csi_vol_scaledown.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-scaledown $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Deprovision Liveness on application and verify the status" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 5 #
################

echo "****Deprovision busybox Application****"

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-csi-vol-scaledown metadata='')
echo $test_name

cd cstor-operators/e2e-tests
echo "Running the e2e test for busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml busybox_dep_csi_vol_scaledown.yml

sed -i -e 's/value: app-busybox-ns/value: csi-vol-scaledown/g' \
-e 's/app: busybox-e2e/app: busybox-dep-csi-vol-scaledown/g' \
-e 's/generateName: e2e-busybox-deploy-/generateName: e2e-busybox-dep-csi-vol-scaledown-/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi-single-replica/g' busybox_dep_csi_vol_scaledown.yml

cat busybox_dep_csi_vol_scaledown.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-dep-csi-vol-scaledown' job=busybox_dep_csi_vol_scaledown.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-scaledown $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

return_count=$?
current_time=$(eval $time)

if [ "$return_count" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-scaledown jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Deprovision the busybox application and verify the status" Fail "$current_time" $#gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-scaledown jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FCO06 3-functional "Deprovision the busybox application and verify the status" Pass "$current_time" $#gittoken

if [ "$return_count" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
