#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FJO01-app-deploy-jiva-rwx node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=3FJO01
time="date"
source ~/.profile
gittoken=$(echo "$github_token")
commit_id=$(echo $3)
releaseTag=$(echo $4)
current_time=$(eval $time)

oc adm policy add-scc-to-user anyuid system:serviceaccount:app-minio-ns:default

bash openebs-openshift-e2e/utils/e2e-cr jobname:app-deploy-jiva-rwx jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:app-deploy-jiva-rwx jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

run_id="jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=minio-deployment metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests

echo "Running the e2e test.."
cp apps/minio/deployers/run_e2e_test.yml deploy_app_jiva.yml

# Replace the storage class name
sed -i '/name: PROVIDER_STORAGE_CLASS/{n;s/.*/            value: openebs-nfs/}' deploy_app_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_app_jiva.yml

cat deploy_app_jiva.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:minio-e2e' job=deploy_app_jiva.yml

echo "Dumping state of cluster post job run"; echo ""
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;

bash openebs-openshift-e2e/utils/event_updater jobname:app-deploy-jiva-rwx $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################

rc_val=$(echo $?)
test_case_id="3FJO01"
source ~/.profile
gittoken=$(echo "$github_token")

## Check the test status & result from the e2e result custom resource
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:app-deploy-jiva-rwx jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:app-deploy-jiva-rwx jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
