#!/bin/bash

pod(){
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FJO05-jiva-csi-volume-resize node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=3FJO05

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
oc adm policy add-scc-to-user anyuid system:serviceaccount:busybox-csi:default

bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

echo "****Deploying busybox Application using CSI****"

run_id="csi";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-busybox-csi metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml deploy_csi_busybox.yml

sed -i -e 's/value: app-busybox-ns/value: busybox-csi/g' \
-e 's/app: busybox-e2e/app: busybox-e2e-csi/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/generateName: e2e-busybox-deploy-/generateName: e2e-busybox-csi-/g' deploy_csi_busybox.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' deploy_csi_busybox.yml

cat deploy_csi_busybox.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-e2e-csi' job=deploy_csi_busybox.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Provision application using CSI with fsType ext4 and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# e2eBook 2 #
################

echo "****Busybox liveness****"

run_id="csi";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for busybox liveness..."
cp apps/busybox/liveness/run_e2e_test.yml liveness_csi_busybox.yml

sed -i -e 's/liveness: e2e-busybox-liveness/liveness: e2e-busybox-csi-liveness/g' \
-e 's/generateName: e2e-busybox-liveness-/generateName: e2e-busybox-csi-liveness-/g' \
-e 's/value: app-busybox-ns/value: busybox-csi/g' liveness_csi_busybox.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' liveness_csi_busybox.yml

cat liveness_csi_busybox.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:e2e-busybox-csi-liveness' job=liveness_csi_busybox.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Liveness on application and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# e2eBook 3 #
################

run_id="csi";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=csi-volume-resize metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
cp experiments/functional/csi-volume-resize/run_e2e_test.yml run_jiva_volume_resize_test.yml

sed -i -e '/name: APP_PVC/{n;s/.*/            value: openebs-busybox/g}' \
-e '/name: APP_LABEL/{n;s/.*/            value: app=busybox/g}' \
-e '/name: STORAGE_CLASS/{n;s/.*/            value: jiva-csi-sc/g}' \
-e '/name: PV_CAPACITY/{n;s/.*/            value: 5Gi/g}' \
-e '/name: NEW_CAPACITY/{n;s/.*/            value: 10Gi/g}' \
-e '/name: APP_NAMESPACE/{n;s/.*/            value: busybox-csi/g}' run_jiva_volume_resize_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_jiva_volume_resize_test.yml

cat run_jiva_volume_resize_test.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:csi-vol-resize' job=run_jiva_volume_resize_test.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Check if the volume size is changed" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# e2eBook 4 #
################

echo "****Busybox liveness deprovision****"

run_id="dep-csi";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for deprovisioning busybox liveness..."
cp apps/busybox/liveness/run_e2e_test.yml dep_liveness_csi_busybox.yml

sed -i -e 's/liveness: e2e-busybox-liveness/liveness: e2e-busybox-csi-liveness-dep/g' \
-e 's/generateName: e2e-busybox-liveness-/generateName: e2e-busybox-csi-liveness-dep-/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: app-busybox-ns/value: busybox-csi/g' dep_liveness_csi_busybox.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' dep_liveness_csi_busybox.yml

cat dep_liveness_csi_busybox.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:e2e-busybox-csi-liveness-dep' job=dep_liveness_csi_busybox.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Liveness on application and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# e2eBook 5 #
################

echo "****Deprovisioning busybox Application****"

run_id="dep-csi";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-busybox-csi metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for busybox Deployment Deprovision.."
cp apps/busybox/deployers/run_e2e_test.yml dep_csi_busybox.yml

sed -i -e 's/value: app-busybox-ns/value: busybox-csi/g' \
-e 's/app: busybox-e2e/app: busybox-e2e-csi-dep/g' \
-e 's/generateName: e2e-busybox-deploy-/generateName: e2e-busybox-csi-dep-/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' dep_csi_busybox.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' dep_csi_busybox.yml

cat dep_csi_busybox.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-e2e-csi-dep' job=dep_csi_busybox.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-volume-resize $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

return_count=$?
current_time=$(eval $time)

if [ "$return_count" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Deprovision the busybox application and verify the status" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-volume-resize jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO05 3-functional "Deprovision the busybox application and verify the status" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$return_count" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
