#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FJO07-jiva-volume-scaleup node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=3FJO07

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

oc adm policy add-scc-to-user anyuid system:serviceaccount:jiva-replica-scaleup:default

bash openebs-openshift-e2e/utils/e2e-cr jobname:jiva-replica-scaleup jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:jiva-replica-scaleup jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

###########Deploying Busybox Application

################
# e2eBook 1 #
################

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specifc value                                    |
  --------------------------------------------------------------------------------------------------------------------------|
 | e2e job label  | label  | app: busybox-e2e                 | app: deploy-jiva-busybox-rep-scaleup                  |
 | e2e Job name   | name   | generateName: e2e-busybox-deploy | generateName: busybox-provision-jiva-replica-scaleup  |
 | appLabel          | env    | app=busybox                     | app=busybox-jiva-replica                              |
 | deploy type       | env    | statefulset                         | deployment                                            |
 | pvcName           | env    | openebs-busybox                     | busybox-jiva-replica-scaleup                          | 
 | storage clas      | env    | openebs-jiva-csi                | jiva-csi-sc                                           |
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                                  |
  ---------------------------------------------------------------------------------------------------------------------------
EOF

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-jiva-replica-scaleup metadata="")
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for Busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml deploy_busybox_jiva_replica_scale.yml

sed -i -e 's/app: busybox-e2e/app: deploy-jiva-busybox-rep-scaleup/g' \
-e 's/generateName: e2e-busybox-deploy/generateName: busybox-provision-jiva-replica-scaleup/g' \
-e 's/app=busybox/app=busybox-jiva-replica/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/value: openebs-busybox/value: busybox-jiva-replica-scaleup/g' \
-e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' deploy_busybox_jiva_replica_scale.yml

cat deploy_busybox_jiva_replica_scale.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:deploy-jiva-busybox-rep-scaleup' deploy_busybox_jiva_replica_scale.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 3-functional "Verify if the Jiva replicas can be scaled up" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Running Busybox loadgen 

#################
# e2eBook 2 #
#################

run_id="jiva-rep-scaleup";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_jiva_rep_scaleup.yml

# Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                             | 
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: busybox-liveness-app-rep-scaleup       |
 | appLabel          | env    | app=busybox                     | app=busybox-jiva-replica                         | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/app=busybox/app=busybox-jiva-replica/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-app-rep-scaleup/g' busybox_loadgen_jiva_rep_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_jiva_rep_scaleup.yml

cat busybox_loadgen_jiva_rep_scaleup.yml

# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-app-rep-scaleup' job=busybox_loadgen_jiva_rep_scaleup.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-openshift-e2e/utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 3-functional "Verify if the Jiva replicas can be scaled up" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Scaling up the Jiva replicas 

#################
# e2eBook 3 #
#################

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=scaleup-jiva-replica metadata="")
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/functional/scale_jiva_csi_replica/run_e2e_test.yml busybox_scale_jiva_rep.yml

 # Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-percona-ns                      | jiva-replica-scaleup                             |  
 | appPVC            | env    | percona-mysql-claim                 | busybox-jiva-replica-scaleup                     |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app-percona-ns/jiva-replica-scaleup/g' \
-e 's/percona-mysql-claim/busybox-jiva-replica-scaleup/g'  busybox_scale_jiva_rep.yml

cat  busybox_scale_jiva_rep.yml
 # Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:scaleup-jiva-replica-e2e' job=busybox_scale_jiva_rep.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 3-functional "Verify if the Jiva replicas can be scaled up" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

#Deprovisioning Busybox-loadgen

################
# e2eBook 4 #
################

run_id="deprovision-jiva-rep-scaleup";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_deprovision_jiva_rep_scaleup.yml

# Update the environmental variables in e2e job spec.

: << EOF
  --------------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                                          |
  --------------------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | jiva-replica-scaleup                                        | 
 | appLabel          | env    | app=busybox                     | app=busybox-jiva-replica                                    |
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: busybox-liveness-deprovision-jiva-replica-scaleup |
 | action            | env    | provision                           | deprovision                                                 | 
  ---------------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/app=busybox/app=busybox-jiva-replica/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: e2e-busybox-liveness/generateName: busybox-liveness-dep-replica-scaleup/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-deprovision-replica-scaleup/g' busybox_loadgen_deprovision_jiva_rep_scaleup.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_jiva_rep_scaleup.yml

cat busybox_loadgen_deprovision_jiva_rep_scaleup.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-deprovision-replica-scaleup' job=busybox_loadgen_deprovision_jiva_rep_scaleup.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 4-chaos "Verify if the Jiva replicas can be scaled up" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

###########-Deprovisioning busybox Application

################
# e2eBook 5 #
################
test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-jiva-replica-scaleup metadata="")
echo $test_name

cd jiva-operator/e2e-tests
cp apps/busybox/deployers/run_e2e_test.yml deprovision_busybox_jiva_replica.yml

sed -i -e 's/generateName: e2e-busybox-deploy/generateName: busybox-deprovision-replica-scaleup/g' \
-e 's/app: busybox-e2e/app: deprovision-jiva-busybox-rep-scaleup/g' \
-e 's/app=busybox/app=busybox-jiva-replica/g' \
-e 's/value: openebs-busybox/value: busybox-jiva-replica-scaleup/g' \
-e 's/value: app-busybox-ns/value: jiva-replica-scaleup/g' \
-e 's/value: provision/value: deprovision/g' deprovision_busybox_jiva_replica.yml

cat deprovision_busybox_jiva_replica.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:deprovision-jiva-busybox-rep-scaleup' job=deprovision_busybox_jiva_replica.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:jiva-replica-scaleup $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
return_count=$?
current_time=$(eval $time)

if [ "$return_count" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:jiva-replica-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 3-functional "Verify if the Jiva replicas can be scaled up" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:jiva-replica-scaleup jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO07 3-functional "Verify if the Jiva replicas can be scaled up" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$return_count" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
