#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FJO03-backup-restore-jiva node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$VELERO_VERSION'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
velero_version=$(echo $5)
case_id=3FJO03

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
bash openebs-openshift-e2e/utils/e2e-cr jobname:backup-restore-jiva jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:backup-restore-jiva jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

oc adm policy add-scc-to-user anyuid system:serviceaccount:backup-percona-jiva:default
oc adm policy add-scc-to-user privileged -z velero -n velero

echo "*******Deploying Percona Application****"

run_id="jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
echo "Running the e2e test for Percona Deployment.."

cp apps/percona/deployers/run_e2e_test.yml percona_backup_restore_jiva.yml

sed -i -e 's/app: percona-deployment/app: deploy-percona-backup-restore-jiva/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/value: app-percona-ns/value: backup-percona-jiva/g' percona_backup_restore_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_backup_restore_jiva.yml

cat percona_backup_restore_jiva.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:deploy-percona-backup-restore-jiva' job=percona_backup_restore_jiva.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:backup-restore-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO03 3-functional "Create backup using velero and verify if it can be successfully restored" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# e2eBook 2 #
################

echo "*******Performing Backup and Restore on percona Application**********"

run_id="jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=velero-backup-restore metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
cp experiments/functional/backup_and_restore/run_e2e_test.yml run_backuprestore_jiva_test.yml

sed -i -e 's/value: app-percona-ns/value: backup-percona-jiva/g' \
-e 's/app: velero-backup-restore/app: velero-backup-restore-jiva/g' \
-e 's/value: percona-backup/value: percona-backup-jiva/g' run_backuprestore_jiva_test.yml

sed -i "s/v1.1.0/$velero_version/g" run_backuprestore_jiva_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_backuprestore_jiva_test.yml

echo "Running the e2e test for Percona Backup Restore.."
cat run_backuprestore_jiva_test.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:velero-backup-restore-jiva' job=run_backuprestore_jiva_test.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:backup-restore-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:backup-restore-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO03 3-functional "Create backup using velero and verify if it can be successfully restored" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:backup-restore-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
##python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 3FJO03 3-functional "Create backup using velero and verify if it can be successfully restored" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
