#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/3-functional/3FJO02-app-replica-scaleup node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=3FJO02

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

oc adm policy add-scc-to-user anyuid system:serviceaccount:app-scale-jiva:default

bash openebs-openshift-e2e/utils/e2e-cr jobname:app-replica-scaleup-jiva jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash openebs-openshift-e2e/utils/e2e-cr jobname:app-replica-scaleup-jiva jobphase:Running

##Deploying Busybox-sts Application

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-app-scale-jiva metadata="") 
echo $test_name

################
# e2eBook 1 #
################

cd jiva-operator/e2e-tests
echo "Running the e2e test for Busybox Deployment.."
cp apps/busybox/deployers/run_e2e_test.yml deploy_run_test_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox                     | app=busybox-scale-jiva                           |
 | appNamespace      | env    | app-busybox-ns                      | app-scale-jiva                                   | 
 | storage class     | env    | openebs-jiva-csi                | jiva-csi-sc                          |
 | Action            | env    | value: provision                    | value: deprovision                               |
 | e2e Job name   | name   | generateName: e2e-busybox-deploy | generateName: busybox-provision-app-replica      |
 | e2e job label  | label  | app: busybox-e2e                 | app:busybox-replica-scale-jiva                   |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/generateName: e2e-busybox-deploy/generateName: busybox-provision-app-replica/g' \
-e 's/value: app-busybox-ns/value: app-scale-jiva/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/app: busybox-e2e/app: busybox-replica-scale-jiva/g' \
-e 's/value: '\''replicas=2'\''/value: '\''replicas=1'\''/g' \
-e 's/value: '\''app=busybox'\''/value: '\''app=busybox-scale-jiva'\''/g' \
-e 's/value: deployment/value: statefulset/g' deploy_run_test_jiva.yml

cat deploy_run_test_jiva.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-replica-scale-jiva' job=deploy_run_test_jiva.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:app-replica-scaleup-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##Deploying loadgen and liveness****"

#################
# e2eBook 2 #
################

run_id="replica";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_replica_scaleup_jiva.yml

 # Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-scale-jiva                                   | 
 | appLabel          | env    | app=busybox                     | app=busybox-scale-jiva                           | 
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: bb-liveness-replica-scaleup            |  
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: app-scale-jiva/g' \
-e 's/app=busybox/app=busybox-scale-jiva/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: bb-liveness-replica-scaleup/g' busybox_loadgen_replica_scaleup_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_replica_scaleup_jiva.yml

cat busybox_loadgen_replica_scaleup_jiva.yml

 # Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:bb-liveness-replica-scaleup' job=busybox_loadgen_replica_scaleup_jiva.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:app-replica-scaleup-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

####Scaling Application replicas

run_id="jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=scale-app-replicas metadata=${run_id})
echo $test_name

################
# e2eBook 3 #
################

cd jiva-operator/e2e-tests
cp experiments/functional/scale_app_replica/run_e2e_test.yml run_scaleup_test_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=cassandra                       | app=busybox-scale-jiva                           | 
 | appNamespace      | env    | app-cass-ns                         | busybox-scale-jiva                               | 
 | e2e job label  | label  | app: cassandra-scaleup-e2e       | app:  scaleup-e2e-jiva                        |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app: cassandra-scaleup-e2e/app: scaleup-e2e-jiva/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/value: '\''app=cassandra'\''/value: '\''app=busybox-scale-jiva'\''/g' \
-e 's/value: app-cass-ns/value: app-scale-jiva/g' run_scaleup_test_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_scaleup_test_jiva.yml

###Running the e2e test for Busybox Deployment Scaleup
cat run_scaleup_test_jiva.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:scaleup-e2e-jiva' job=run_scaleup_test_jiva.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:app-replica-scaleup-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

##Deprovisioning loadgen and liveness 

################
# e2eBook 4 #
################

run_id="dep-replica";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml bb_loadgen_dep_app_scaleup_jiva.yml

 # Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | app-scale-jiva                                   | 
 | action            | env    | provision                           | deprovision                                      |
 | appLabel          | env    | app=busybox                     | app=busybox-scale-jiva                           |  
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: bb-liveness-dep-replica                |
 ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: app-scale-jiva/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/app=busybox/app=busybox-scale-jiva/g' \
-e 's/generateName: e2e-busybox-liveness/generateName: busybox-liveness-dep-replica/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: bb-liveness-dep-replica/g' bb_loadgen_dep_app_scaleup_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' bb_loadgen_dep_app_scaleup_jiva.yml

cat bb_loadgen_dep_app_scaleup_jiva.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:bb-liveness-dep-replica' job=bb_loadgen_dep_app_scaleup_jiva.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:app-replica-scaleup-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

 # Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
exit 1;
fi

####Deprovisioning Busybox Application

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-app-scale-jiva metadata="")
echo $test_name

################
# e2eBook 5 #
################

cd jiva-operator/e2e-tests
cp apps/busybox/deployers/run_e2e_test.yml deprovision_scaleup_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox                     | app=busybox-scale-jiva                           | 
 | appNamespace      | env    | app-busybox-ns                      | app-scale-jiva                                   | 
 | storage clas      | env    | openebs-jiva-csi                | jiva-csi-sc                             |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | Action            | env    | value: provision                    | value: deprovision                               |
 | e2e Job name   | name   | generateName: e2e-busybox-deploy | generateName: busybox-deprovision-target-affinity|
 | e2e job label  | label  | app: busybox-e2e                 | app: busybox-deprovision-e2e-jiva             |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: e2e-busybox-deploy/generateName: busybox-deprovision-app-replica/g' \
-e 's/value: app-busybox-ns/value: app-scale-jiva/g' \
-e 's/app: busybox-e2e/app: busybox-deprovision-e2e-jiva/g' \
-e 's/value: '\''app=busybox'\''/value: '\''app=busybox-scale-jiva'\''/g' \
-e 's/value: '\''replicas=2'\''/value: '\''replicas=1'\''/g' \
-e 's/value: openebs-jiva-csi/value: jiva-csi-sc/g' \
-e 's/value: deployment/value: statefulset/g' \
-e 's/value: provision/value: deprovision/g' deprovision_scaleup_jiva.yml

cat deprovision_scaleup_jiva.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-deprovision-e2e-jiva' job=deprovision_scaleup_jiva.yml
cd ../..
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:app-replica-scaleup-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:app-replica-scaleup-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:app-replica-scaleup-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
