#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/4E0O-Storage-Volume-scaleup/storage-volume-scaleup node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo $job_id
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > storage-vol-scaleup-$job_id.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/storage-vol-scaleup/g" -e"s/<job_id>/$job_id/g" storage-vol-scaleup-$job_id.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" storage-vol-scaleup-$job_id.yml
kubectl apply -f storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml

echo "*******Deploying Application****"
sleep 5
echo "      Application-Deployment: Pass" >> storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml
kubectl apply -f storage-vol-scaleup-$job_id.yml

echo "*******Generating load**********"
sleep 5
echo "      Application-Loadgen: Pass" >> storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml
kubectl apply -f storage-vol-scaleup-$job_id.yml

echo "*******Scaling up the storage volume************"
sleep 5
echo "      Storage-Vol-Scaleup: Fail" >> storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml
kubectl apply -f storage-vol-scaleup-$job_id.yml

echo "*******Deprovisioning Application******"
sleep 5
echo "      Application-Deprovisioning: Pass" >> storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml
kubectl apply -f storage-vol-scaleup-$job_id.yml

current_time=$(eval $time)
sed -i -e "s/<test-finish>/$current_time/g" storage-vol-scaleup-$job_id.yml
sed -i -e "s/<test-result>/Fail/g" storage-vol-scaleup-$job_id.yml
sed -i -e "s/Running/Completed/g" storage-vol-scaleup-$job_id.yml
cat storage-vol-scaleup-$job_id.yml
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
