#!/bin/bash
set -x

pod() {
### Drain the node to run infra chaos test scripts
echo "******* Drain node for maintainence ********"

node_name=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes | grep compute | awk 'FNR==1 {print $1}')

echo $node_name
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/5-infra-chaos/T1JZ-node-failure-jiva/node-failure-jiva node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$node_name'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=T1JZ
observer_node=$4
releaseTag=$(echo $5)


time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
bash Openshift-EE/utils/pooling jobname:node-failure-cstor
bash Openshift-EE/utils/e2e-cr jobname:node-failure-jiva jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox-Deployment****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-node-failure-jiva metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml app_deploy_node_failure_jiva.yml

: << EOF
  -------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specific value                             |
  -------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | taint-node                                     |
 | Litmus job label  | label  | app: busybox-litmus                 | app: node-failure-jiva                        | 
 | appLabel          | env    | app=busybox-sts                     | app=taint-node                                 |
 | storage class     | env    | openebs-cstor-sparse                | openebs-jiva-default                           |
 | deploy type       | env    | statefulset                         | deployment                                     |
  --------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app-busybox-ns/node-failure-jiva/g' \
-e 's/busybox-litmus/node-failure-jiva/g' \
-e 's/app=busybox-sts/app=node-failure-jiva/g' \
-e 's/openebs-cstor-sparse/openebs-jiva-default/g' \
-e 's/statefulset/deployment/g' app_deploy_node_failure_jiva.yml

cat app_deploy_node_failure_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:node-failure-jiva' app_deploy_node_failure_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:node-failure-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken

exit 1;
fi

################
# LitmusBook 2 #
################

run_id="node-failure-jiva";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_node_failure_jiva.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ----------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | node-failure-jiva                                | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-node-failure-jiva     |
 | appLabel          | env    | app=busybox-sts                     | app=node-failure-jiva                            | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: node-failure-jiva/g' \
-e 's/app=busybox-sts/app=node-failure-jiva/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-node-failure-jiva/g' busybox_loadgen_node_failure_jiva.yml

cat busybox_loadgen_node_failure_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_node_failure_jiva.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-node-failure-jiva' job=busybox_loadgen_node_failure_jiva.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:node-failure-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

run_id="jiva"; test_name=$(bash Openshift-EE/utils/generate_test_name testcase=node-failure metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/node_failure/run_litmus_test.yml run_node_failure_jiva.yml

sed -i -e 's/value: app-percona-ns/value: node-failure-jiva/g' \
-e 's/name: node-failure/name: node-failure-jiva/g' \
-e 's/password:/password: YzEwdWRieXQzQDE2NTg=/g' \
-e 's/name=percona/app=node-failure-jiva/g' run_node_failure_jiva.yml

sed -i -e "s|#nodeSelector|nodeSelector|g" \
-e "s|#  kubernetes.io/hostname:|  kubernetes.io/hostname: ${observer_node}|g" run_node_failure_jiva.yml

sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_node_failure_jiva.yml

sed -i '/name: ESX_HOST_IP/{n;s/.*/            value: 10.23.1.1/}' run_node_failure_jiva.yml

sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: nodefailure
' run_node_failure_jiva.yml

cat run_node_failure_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:node-failure-jiva' run_node_failure_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:node-failure-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-node-failure-jiva";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_node_failure_jiva.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | node-failure-jiva                                       | 
 | appLabel          | env    | app=busybox-sts                     | app=node-failure-jiva                                   |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-node_failure-jiva |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: node-failure-jiva/g' \
-e 's/app=busybox-sts/app=node-failure-jiva/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-node-failure-jiva/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-node-failure-jiva/g' busybox_loadgen_deprovision_node_failure_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_node_failure_jiva.yml

cat busybox_loadgen_deprovision_node_failure_jiva.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-node-failure-jiva' job=busybox_loadgen_deprovision_node_failure_jiva.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:node-failure-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-node-failure-jiva metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_node_failure_jiva.yml

: << EOF
  -------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                             |
  -------------------------------------------------------------------------------------------------------------------|
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName:litmus-busybox-deprovision        |
 | appNamespace      | env    | app-busybox-ns                      | node-failure-jiva                                     |
 | appLabel          | env    | app=busybox-sts                     | app=node-failure-jiva                                |
 | deploy type       | env    | statefulset                         | deployment                                     |
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-node-failure-jiva                | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-jiva-default                             |
 | Action            | env    | provision                           | deprovision                                    |
  --------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: litmus-busybox-deprovision-jiva/g' \
-e 's/app-busybox-ns/node-failure-jiva/g' \
-e 's/app=busybox-sts/app=node-failure-jiva/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/busybox-litmus/busybox-deprovision-node-failure-jiva/g' \
-e 's/openebs-cstor-sparse/openebs-jiva-default/g' \
-e 's/value: provision/value: deprovision/g' deprovision_node_failure_jiva.yml

cat deprovision_node_failure_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-node-failure-jiva' deprovision_node_failure_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:node-failure-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:node-failure-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:node-failure-jiva jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id T1JZ 5-infra-chaos "Fail the node where the application on jiva volume is running and check the behaviour" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
