#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/4-migrate-openebs/migrate-cstor-volume node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$TO_VERSION'"' '"'$UPGRADE_IMAGE_TAG'"'
}


node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
to_version=$(echo $4)
upgrade_imageTag=$(echo $5)


present_dir=$(pwd)
echo $present_dir


bash openebs-openshift-e2e/script/utils/pooling jobname:migrate-cstor-pool
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:migrate-cstor-volume jobphase:Waiting
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:migrate-cstor-volume jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag"

run_id="volume";test_name=$(bash openebs-openshift-e2e/script/utils/generate_test_name testcase=cstor-cspc-csi-migration metadata=${run_id})
echo $test_name

git clone https://github.com/openebs/upgrade
cd upgrade/e2e-tests
echo "Running the e2e test.."

cp experiments/cspc_csi_migration/run_e2e_test.yml migrate-cstor-volume.yml

sed -i -e '/name: MIGRATE_CSTOR_VOLUME/{n;s/.*/            value: "true"/}' \
-e '/name: OPERATOR_IMAGE_TAG/{n;s/.*/            value: '"'$to_version'"'/}' \
-e '/name: MIGRATATION_IMAGE_TAG/{n;s/.*/            value: '"'$upgrade_imageTag'"'/}' \
-e 's/app: cspc-csi-migration/app: cspc-csi-volume-migration/g' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' migrate-cstor-volume.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' migrate-cstor-volume.yml

cat migrate-cstor-volume.yml

bash ../../openebs-openshift-e2e/script/utils/e2e_job_runner label='app:cspc-csi-volume-migration' job=migrate-cstor-volume.yml

echo "Dumping state of cluster post job run"; echo ""
bash ../../openebs-openshift-e2e/script/utils/dump_cluster_state;

cd ../..
bash openebs-openshift-e2e/script/utils/event_updater jobname:migrate-cstor-volume $test_name jobid:"$job_id" pipelineid:"$pipeline_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)
kubectl get pods -n openebs -o yaml | grep image | grep -v imageID | grep quay

## Check the test status & result from the e2e result custom resource
source ~/.profile
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:migrate-cstor-volume jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi
