#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/UURF-Jiva-sts-App-Target-Affinity/sts-app-target-affinity node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=UURF

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:sts-app-target-affinity-jiva jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash Openshift-EE/utils/e2e-cr jobname:sts-app-target-affinity-jiva jobphase:Running

################
# LitmusBook 1 #
################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-sts-affinity-jiva metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deploy_sts_affinity_test_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=sts-target-affinity-jiva                     |
 | pvcName           | env    | openebs-busybox                     | busybox-sts-target-affinity-jiva                 | 
 | appNamespace      | env    | app-busybox-ns                      | sts-affinity-jiva                                | 
 | storage clas      | env    | openebs-cstor-sparse                | openebs-jiva-default                             |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-provision-sts-affinity-jiva|
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-litmus-sts-target-affinity-jiva     |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/generateName: litmus-busybox-deploy/generateName: busybox-provision-sts-affinity-jiva/g' \
-e 's/app: busybox-litmus/app: busybox-litmus-sts-target-affinity-jiva/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=sts-target-affinity-jiva'\''/g' \
-e 's/value: openebs.io\/target-affinity/value: openebs.io\/sts-target-affinity/g' \
-e 's/value: app-busybox-ns/value: sts-affinity-jiva/g' \
-e 's/value: openebs-busybox/value: busybox-sts-target-affinity-jiva/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' deploy_sts_affinity_test_jiva.yml

cat deploy_sts_affinity_test_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-litmus-sts-target-affinity-jiva' job=deploy_sts_affinity_test_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Statefulset Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deploying loadgen and liveness

#################
# LitmusBook 2 #
################

run_id="affinity";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_app_target_affinity.yml

 # Update the environmental variables in litmus job spec.

 : << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | sts-affinity-jiva                                | 
 | appLabel          | env    | app=busybox-sts                     | app=sts-target-affinity-jiva                     | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness:busybox-liveness-app-target-affinity    | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value:  sts-affinity-jiva/g' \
-e 's/app=busybox-sts/app=sts-target-affinity-jiva/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-app-target-affinity/g'  busybox_loadgen_app_target_affinity.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_app_target_affinity.yml

cat busybox_loadgen_app_target_affinity.yml
 # Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-app-target-affinity' job=busybox_loadgen_app_target_affinity.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi


echo "*******Checking Application and Target Pod Affinity **********"

################
# LitmusBook 3 #
################

run_id="jiva-sts";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=app-target-affinity metadata=${run_id})
echo $test_name

cd litmus
cp experiments/functional/app-target-affinity/run_litmus_test.yml run_sts_affinity_test_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value                     | test specifc value                              |
  --------------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                           | app=sts-target-affinity-jiva                    | 
 | appNamespace      | env    | app-busybox-ns                            | sts-affinity-jiva                               | 
 | Litmus Job name   | name   | generateName: litmus-app-target-affinity- | generateName: litmus-sts-target-affinity-jiva-  |
 | Litmus job label  | label  | app: litmus-affinity                      | app: litmus-sts-affinity-jiva                   |
  ---------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/app: litmus-affinity/app: litmus-sts-affinity-jiva/g' \
-e 's/value: app=busybox-sts/value: app=sts-target-affinity-jiva/g' \
-e 's/value: deployment/value: statefulset/g' \
-e 's/generateName: litmus-app-target-affinity-/generateName: litmus-sts-target-affinity-jiva-/g' \
-e 's/value: app-busybox-ns/value: sts-affinity-jiva/g' run_sts_affinity_test_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_sts_affinity_test_jiva.yml

cat run_sts_affinity_test_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:litmus-sts-affinity-jiva' job=run_sts_affinity_test_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Statefulset Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deprovisioning loadgen and liveness 

################
# LitmusBook 4 #
################

run_id="dep-sts";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml loadgen_deprovision_app_target_affinity.yml

 # Update the environmental variables in litmus job spec.

 : << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | sts-affinity-jiva                                | 
 | action            | env    | provision                           | deprovision                                      |
 | appLabel          | env    | app=busybox-sts                     | app=sts-target-affinity-jiva                     |  
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: liveness-deprovision-app-target-affinity |
 ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-affinity-jiva/g' \
-e '/svalue: provision/value: deprovision/g' \
-e 's/app=busybox-sts/app=sts-target-affinity-jiva/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-app-target-affinity/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: liveness-deprovision-app-target-affinity/g' loadgen_deprovision_app_target_affinity.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' loadgen_deprovision_app_target_affinity.yml

cat  busybox_loadgen_deprovision_app_target_affinity.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-app-target-affinity' job= loadgen_deprovision_app_target_affinity.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

 rc_val=$(echo $?)

 # Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Statefulset Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deprovisioning Busybox Application

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-sts-affinity-jiva metadata="")
echo $test_name

################
# LitmusBook 5 #
################

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_sts_affinity_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=sts-target-affinity-jiva                     |
 | pvcName           | env    | openebs-busybox                     | busybox-sts-target-affinity-jiva                 | 
 | appNamespace      | env    | app-busybox-ns                      | sts-affinity-jiva                                | 
 | storage clas      | env    | openebs-cstor-sparse                | openebs-jiva-default                             |
 | Action            | env    | value: provision                    | value: deprovision                               |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-deprovision-target-affinity|
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-sts-affinity-jiva       |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-sts-target-affinity/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-sts-affinity-jiva/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=sts-target-affinity-jiva'\''/g' \
-e 's/value: app-busybox-ns/value: sts-affinity-jiva/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-sts-affinity-jiva/g' \
-e 's/value: openebs-busybox/value: busybox-sts-target-affinity-jiva/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' \
-e 's/value: provision/value: deprovision/g' deprovision_sts_affinity_jiva.yml

cat deprovision_sts_affinity_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-sts-affinity-jiva' job=deprovision_sts_affinity_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva  $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:sts-app-target-affinity-jiva  jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Statefulset Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:sts-app-target-affinity-jiva  jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id UURF 3-functional "Checking Statefulset Application and target scheduled on same Node" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
