#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone -b OpenEBS-base https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/QCA4-target-network-loss/target-network-loss node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
case_id=QCA4

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:target-loss jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:target-loss jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-target-loss metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_target_loss.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-target-loss/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetloss/g' \
-e 's/value: app-busybox-ns/value: target-loss/g' busybox_target_loss.yml
cat busybox_target_loss.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-target-loss' job=busybox_target_loss.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Pass $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

echo "*******Performing Network loss on target**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-target-network-loss metadata="")
echo $test_name

cd litmus
cp apps/percona/chaos/openebs_target_network_loss/run_litmus_test.yml run_targetloss_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-targetloss/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=target-loss'\''/g' \
-e 's/value: '\''enable'\''/value: '\'""\''/g' \
-e 's/value: app-percona-ns/value: target-loss/g' run_targetloss_test.yml

echo "Running the litmus test for Busybox Deployment Scaleup.."
cat run_targetloss_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-target-network-loss' job=run_targetloss_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Pass $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-target-loss metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_target_loss.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-target-loss/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-target-loss/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/app=busybox-sts/app=target-loss/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-targetloss/g' \
-e 's/value: app-busybox-ns/value: target-loss/g' \
-e 's/value: provision/value: deprovision/g' deprovision_target_loss.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_target_loss.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-target-loss' job=deprovision_target_loss.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-loss $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

# if [ "$rc_val" != "0" ]; then
# exit 1;
# fi

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:target-loss jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id QCA4 4-chaos "Induce cstor target network loss and check if it gets recovered successfully" Pass $testResult $pipeline_id "$current_time" $commit_id $gittoken

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
