#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/VTPW-cvr-migration/cvr-migration node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=VTPW

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:cvr-migration jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:cvr-scaleup jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:cvr-migration jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

###########Deploying Busybox Application

################
# LitmusBook 1 #
################

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specific value                                   |
  --------------------------------------------------------------------------------------------------------------------------|
 | Litmus job label  | label  | app: busybox-litmus                 | app: deploy-busybox-cvr-migration                     |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-provision-cvr-migration         |
 | appLabel          | env    | app=busybox-sts                     | app=busybox-cvr-migration                             |
 | deploy type       | env    | statefulset                         | deployment                                            |
 | pvcName           | env    | openebs-busybox                     | busybox-cvr-migration                                 | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                                    |
 | appNamespace      | env    | app-busybox-ns                      | cvr-migration                                         |
  ---------------------------------------------------------------------------------------------------------------------------
EOF

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-cvr-migration metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml deploy_busybox_cvr_migration.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-cvr-migration/g' \
-e 's/generateName: litmus-busybox-deploy/generateName: busybox-provision-cvr-migration/g' \
-e 's/app=busybox-sts/app=busybox-cvr-migration/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: openebs-busybox/value: busybox-cvr-migration/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: app-busybox-ns/value: cvr-migration/g' deploy_busybox_cvr_migration.yml

cat deploy_busybox_cvr_migration.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-cvr-migration' deploy_busybox_cvr_migration.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cvr-migration $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 3-functional "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Running Busybox loadgen 

#################
# LitmusBook 2 #
#################

run_id="cvr-migration";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_cvr_migration.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specific value                              |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | cvr-migration                                  | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-cvr-migrate         |
 | appLabel          | env    | app=busybox-sts                     | app=busybox-cvr-migration                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: cvr-migration/g' \
-e 's/app=busybox-sts/app=busybox-cvr-migration/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-cvr-migrate/g' busybox_loadgen_cvr_migration.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_cvr_migration.yml

cat busybox_loadgen_cvr_migration.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-cvr-migrate' job=busybox_loadgen_cvr_migration.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:cvr-migration $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 3-functional "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

## Migrating the cvr to other pool

#################
# LitmusBook 3 #
#################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=cstor-volume-replica-migration metadata="")
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp experiments/functional/cstor-volume-migration/run_litmus_test.yml busybox_volume_migration.yml

 # Update the environmental variables in litmus job spec.

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: cvr-migration/}' \
-e '/name: OPERATOR_NS/{n;s/.*/            value: openebs/}' \
-e '/name: PVC_NAME/{n;s/.*/            value: busybox-cvr-migration/}' busybox_volume_migration.yml

cat  busybox_volume_migration.yml
 # Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='app:cvr-migration' job=busybox_volume_migration.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cvr-migration $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 3-functional "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

#Deprovisioning Busybox-loadgen

################
# LitmusBook 4 #
################

run_id="deprovision-cvr-migration";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_cvr_migration.yml

# Update the environmental variables in litmus job spec.

: << EOF
  --------------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specific value                                          |
  --------------------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | cvr-migration                                               | 
 | appLabel          | env    | app=busybox-sts                     | app=busybox-cvr-migration                                   |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-cvr-migration        |
 | action            | env    | provision                           | deprovision                                                 | 
  ---------------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: cvr-migration/g' \
-e 's/app=busybox-sts/app=busybox-cvr-migration/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-cvr-migration/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-cvr-migration/g' busybox_loadgen_deprovision_cvr_migration.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_cvr_migration.yml

cat busybox_loadgen_deprovision_cvr_migration.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-cvr-migration' job=busybox_loadgen_deprovision_cvr_migration.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cvr-migration $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-konvoy repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 4-chaos "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

###########-Deprovisioning busybox Application

################
# LitmusBook 5 #
################
test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-cvr-migration metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_busybox_cvr_migration.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-cvr-migration/g' \
-e 's/app: busybox-litmus/app: deprovision-cvr-migration/g' \
-e 's/app=busybox-sts/app=busybox-cvr-migration/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: busybox-cvr-migration/g' \
-e 's/value: app-busybox-ns/value: cvr-migration/g' \
-e 's/value: provision/value: deprovision/g' deprovision_busybox_cvr_migration.yml

cat deprovision_busybox_cvr_migration.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deprovision-cvr-migration' job=deprovision_busybox_cvr_migration.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:cvr-migration $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
return_count=$?

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
current_time=$(eval $time)

if [ "$return_count" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:cvr-migration jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 3-functional "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:cvr-migration jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult
python3 Openshift-EE/utils/result/result_update.py $job_id VTPW 3-functional "Verify the CVR migrated successfully from one pool to another pool and check the volume status is healthy" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$return_count" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
