#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/PX1D-jiva-replica-node-affinity/replica-node-affinity node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
case_id=PX1D

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:jiva-replica-node-affinity jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
bash Openshift-EE/utils/e2e-cr jobname:jiva-replica-node-affinity jobphase:Running

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-replica-node-affinity-jiva metadata="") 
echo $test_name

################
# LitmusBook 1 #
################

cd litmus
echo "Running the litmus test for Busybox Deployment.."
cp apps/busybox/deployers/run_litmus_test.yml deploy_rep_node_affinity.yml

: << EOF
  ------------------------------------------------------------------------------------------------------------------------------|
 | specAttribute     | kind   |         default value               | test specifc value                                        |
  ------------------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=busybox-rep-node-affinity-jiva                        |
 | appNamespace      | env    | app-busybox-ns                      | rep-node-affinity-jiva                                    |   
 | appPVC            | env    | openebs-busybox                     | openebs-busybox-rep-affinity                              |
 | storage class     | env    | openebs-cstor-sparse                | openebs-jiva-default                                      |
 | deploy type       | env    | statefulset                         | deployment                                                |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-provision-replica-node-affinity-jiva|
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-replica-node-affiniy-jiva                    |
  ------------------------------------------------------------------------------------------------------------------------------|
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/generateName: litmus-busybox-deploy/generateName: busybox-provision-replica-node-affinity-jiva/g' \
-e 's/value: app-busybox-ns/value: rep-node-affinity-jiva/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-busybox-rep-affinity/g' \
-e 's/app: busybox-litmus/app: busybox-replica-node-affiniy-jiva/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=busybox-rep-node-affinity-jiva'\''/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' deploy_rep_node_affinity.yml

cat deploy_rep_node_affinity.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-replica-node-affiniy-jiva' job=deploy_rep_node_affinity.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:jiva-replica-node-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PX1D 4-chaos "Jiva replica node affinity" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="jiva";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-replica-network-delay metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/replica_node_affinity/run_litmus_test.yml run_rep_node_affinity_jiva.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=pgset                           | app=busybox-rep-node-affinity-jiva               | 
 | appPVC            | env    | value: pgdata-claim                 | value: openebs-busybox-rep-affinity              |
 | appNamespace      | env    | app-pgres-ns                        | rep-node-affinity-jiva                           | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/name=percona/app=busybox-rep-node-affinity-jiva/g' \
-e 's/value: app-pgres-ns/value: rep-node-affinity-jiva/g' \
-e 's/value: pgdata-claim/value: openebs-busybox-rep-affinity/g' run_rep_node_affinity_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_rep_network_delay_jiva.yml

cat run_rep_network_delay_jiva.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:node-affinity' job=run_rep_network_delay_jiva.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:jiva-replica-node-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PX1D 4-chaos "Jiva replica node affinity" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase= busybox-deprovision-rep-node-affinity-jiva metadata="")
echo $test_name

################
# LitmusBook 3 #
################

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_rep_node_affinity.yml

: << EOF
  -----------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                                       |
  -----------------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=busybox-rep-node-affinity-jiva                       | 
 | appNamespace      | env    | app-busybox-ns                      | rep-node-affinity-jiva                                   |   
 | storage clas      | env    | openebs-cstor-sparse                | openebs-jiva-default                                     |
 | deploy type       | env    | statefulset                         | deployment                                               |
 | Action            | env    | value: provision                    | value: deprovision                                       |
 | Litmus Job name   | name   | generateName: litmus-busybox-deploy | generateName: busybox-deprovision-rep-node-affinity-jiva |
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-rep-node-affinity               |
  -----------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-rep-node-affinity-jiva /g' \
-e 's/value: app-busybox-ns/value: rep-node-affinity-jiva/g' \
-e 's/app: busybox-litmus/app:  busybox-deprovision-rep-node-affinity/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=busybox-rep-node-affinity-jiva'\''/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-jiva-default/g' \
-e 's/value: provision/value: deprovision/g' deprovision_rep_node_affinity.yml

cat deprovision_rep_node_affinity.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-rep-node-affinity' job=deprovision_rep_node_affinity.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:jiva-replica-node-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PX1D 4-chaos "Jiva replica node affinity" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:jiva-replica-node-affinity jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id PX1D 4-chaos "Jiva replica node affinity" Pass $pipeline_id "$current_time" $commit_id $gittoken
}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
