#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/Cassandra/stages/5-cleanup/WWDM-cassandra-cleanup/delete-cassandra node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

#Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
job_id=$1

# Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
pipeline_id=$2 

#Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).
commit_id=$3 

#test case ID.
case_id=WWDM

#github token to push the test result into github mayadata-io/e2e-openshift repository.
#This token is set as an env in ~/.profile file in the test cluster.
source ~/.profile
gitToken=$github_token

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir


#Creating e2e custom resource result for the test.
bash Openshift-EE/utils/e2e-cr jobname:delete-cassandra jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:delete-cassandra jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
bash Openshift-EE/utils/e2e-cr jobname:delete-cluster jobphase:Waiting


#### Deleting Cassandra application

run_id="delete"; test_name=$(bash Openshift-EE/utils/generate_test_name testcase=cassandra-deployment metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/cassandra/deployers/run_litmus_test.yml delete_cassandra.yml

# Update the environmental variables in litmus job spec.
: << EOF
 ----------------------------------------------------------------------------------------------------------------------     
 | specAttribute     | kind   |         default value               | test specifc value                              |
 |--------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=cassandra                       | app=cassandra                                   |
 | pvcName           | env    | openebs-cassandra                   | openebs-cassandra                               | 
 | storage class     | env    | openebs-standalone                  | openebs-cstor-sparse                            |
 | appNamespace      | env    | app-cass-ns                         | app-cass-ns                                     |
 | action            | env    | provision        		    | deprovision                                     |
 ----------------------------------------------------------------------------------------------------------------------
EOF
# Replacing the required parameters in the litmus experiment.

sed -i -e 's/value: openebs-standalone/value: openebs-cstor-sparse/g'\
       -e 's/value: provision/value: deprovision/g'\
       -e 's/app: cassandra-deployment-litmus/app: cassandra-delete-litmus/g' delete_cassandra.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' delete_cassandra.yml

cat delete_cassandra.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='app:cassandra-delete-litmus' job=delete_cassandra.yml
cd ..

# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:delete-cassandra $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
rc_val=$(echo $?)
# Obtain the status of the test using litmusresult(lr) 
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id $case_id 5-cleanup "Check if the cassandra ring is deleted successfully" $testResult $pipeline_id "$current_time" $commit_id $gitToken
exit 1;
fi


# Update the e2e cr once the job is completed
bash Openshift-EE/utils/e2e-cr jobname:delete-cassandra jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

python3 Openshift-EE/utils/result/result_update.py $job_id $case_id 5-cleanup "Check if the cassandra ring is deleted successfully" $testResult $pipeline_id "$current_time" $commit_id $gitToken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi

