#!/bin/bash
set -x
pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/2-setup/1CXH-storage-policies/openebs-sc node '"'$CI_JOB_ID'"''
}

node() {

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

# Removing test_id from e2e-result.yml spec for simple mode
sed -i "s/-<job_id>/ /g" Openshift-EE/utils/e2e-result.yml

#pooling over previous job to complete
echo "***********Applying openebs-storage-clas********"
bash Openshift-EE/utils/pooling jobname:s2-j2-cstor-pool
bash Openshift-EE/utils/e2e-cr jobname:s2-j3-policies jobphase:Running init_time:"$current_time"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=cstor-storage-policies metadata="")
echo $test_name

cd litmus
echo "Running the litmus test.."

run_test=providers/cstor-storage-policies/run_litmus_test.yml

cat $run_test

bash ../Openshift-EE/utils/litmus_job_runner label='app:cstor-storage-policy' job=$run_test

echo "Dumping state of cluster post job run"; echo ""
bash ../Openshift-EE/utils/dump_cluster_state;

#################
## GET RESULT  ##
#################

## Check the test status & result from the litmus result custom resource

cd .. && bash Openshift-EE/utils/get_litmus_result ${test_name} s2-j3-policies

}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
