#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/II1Z-pool-network-delay/pool-network-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=II1Z
commit_id=$(echo $3)
time="date"
current_time=$(eval $time)
source ~/.profile
gittoken=$(echo "$github_token")
present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/pooling jobname:volume-istgt-kill 
bash Openshift-EE/utils/e2e-cr jobname:pool-network-delay jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

################
# LitmusBook 3 #
################
# Performing network delay in cStor Pool

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-cstor-pool-network-delay metadata="")
echo $test_name

cd litmus
cp experiments/chaos/openebs_pool_network/run_litmus_test.yml run_pooldelay_test.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------    
 | specAttribute       | kind   |         default value                 | test specifc value                          |
  --------------------------------------------------------------------------------------------------------------------|
 | appNamespace        | env    | app-percona-ns                        | app-esearch-ns                              |
 | appLabel            | label  | name=percona                          | app=elasticsearch                           |
 | livenessAppLabel    | label  |  ""                                   | liveness=elasticsearch-liveness             |
 | livenessAppNamespace| env    |  ""                                   | app-esearch-ns                              |
 | appPVC              | env    | percona-mysql-claim                   |  openebs-elasticsearch-logging-0            |
   ---------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-percona-ns/value:  app-esearch-ns/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=elasticsearch'\''/g' \
-e '/name: LIVENESS_APP_LABEL/!b;n;c\            \ value: "liveness=elasticsearch-liveness"' \
-e '/name: LIVENESS_APP_NAMESPACE/!b;n;c\            \ value: "app-esearch-ns"' \
-e 's/value: percona-mysql-claim/value: openebs-esearch-elasticsearch-logging-0/g' \ run_pooldelay_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' volume_istgt_kill_test.yml

cat run_pooldelay_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-pool-network' job=run_pooldelay_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id II1Z 4-chaos "Induce Delay in cstor pool pods" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi
