#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/mongodb/stages/4-chaos/NPAT-jiva-replica-network-delay/jiva-replica-network-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

#Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
job_id=$1

# Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
pipeline_id=$2 

#Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).
commit_id=$3 

#test case ID.
case_id=NPAT

#github token to push the test result into github mayadata-io/e2e-openshift repository.
#This token is set as an env in ~/.profile file in the test cluster.
source ~/.profile
gitToken=$github_token

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

#Creating e2e custom resource result for all the tests running in this stage.
#In Gitlab, all the jobs in a stage runs parallely. Inorder to run this serially, each job in the stage waits for the other to get completed.

bash Openshift-EE/utils/pooling jobname:jiva-replica-failure
bash Openshift-EE/utils/e2e-cr jobname:jiva-replica-network-delay jobphase:Running jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

##Generating test name using test case name
run_id="jiva";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-replica-network-delay metadata=${run_id})
echo $test_name

cd litmus
# copy the content of application pod failure chaos `run_litmus_test.yml` into a different file to update the test specific parameters.
cp experiments/chaos/openebs_replica_network_delay/run_litmus_test.yml run_rep_network_delay_jiva.yml

: << EOF
  ----------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value                      | test specifc value                               |
  ----------------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | name=percona                               | app=mongo                                        | 
 | appPVC            | env    | value: percona-mysql-claim                 | value: openebs-mongo-mongo-0                     |
 | Litmus Job name   | name   | generateName: openebs-replica-network-delay| generateName: openebs-replica-network-delay-jiva |
 | Litmus job label  | label  | name: openebs-replica-network              | name: openebs-replica-network-jiva               |
 | appNamespace      | env    | app-percona-ns                             | app-mongo-ns-jiva                                | 
  ----------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: '\''name=percona'\''/value: '\''app=mongo'\''/g' \
-e 's/value: app-percona-ns/value: app-mongo-ns-jiva/g' \
-e 's/generateName: openebs-replica-network-delay/generateName: openebs-replica-network-delay-jiva/g' \
-e 's/name: openebs-replica-network/name: openebs-replica-network-jiva/g' \
-e 's/value: percona-mysql-claim/value: openebs-mongo-mongo-0/g' run_rep_network_delay_jiva.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_rep_network_delay_jiva.yml

cat run_rep_network_delay_jiva.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-replica-network-jiva' job=run_rep_network_delay_jiva.yml
cd ..

# Print the cluster state once the litmus job is completed.
bash Openshift-EE/utils/dump_cluster_state;

# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:jiva-replica-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Obtain the status of the test using litmusresult(lr) 
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

# Update the e2e cr once the job is completed
bash Openshift-EE/utils/e2e-cr jobname:jiva-replica-network-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:$testResult

python3 Openshift-EE/utils/result/result_update.py $job_id $case_id 4-chaos "Inject network delay in jiva replica & verify successful recovery" $testResult $pipeline_id "$current_time" $commit_id $gitToken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi