#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/11-cleanup/RZTG-cleanup-cstor-operator/cleanup-cstor-operator node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=RZTG
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
echo "*******Cleaning cstor-pool**************"
bash Openshift-EE/utils/pooling jobname:cleanup-cspc-mirrored-pool
bash Openshift-EE/utils/e2e-cr jobname:cleanup-cstor-operator jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-cstor-operator-deprovision metadata="")
echo $test_name
cd litmus

cp providers/cstor-operator/run_litmus_test.yaml cstor_operator_deprovision.yml

sed -i -e "/name: CSPC_OPERATOR_IMAGE/{n;s/.*/            value: ${cspc_operator_image}/g}" \
-e 's/value: provision/value: deprovision/g' \
-e 's/provider: cstor-operator/provider: cstor-operator-deprovision/g' \
-e 's/generateName: litmus-cstor-operator-/generateName: litmus-cstor-operator-deprovision-/g' cstor_operator_deprovision.yml

cat cstor_operator_deprovision.yml

bash ../Openshift-EE/utils/litmus_job_runner label='provider:cstor-operator-deprovision' job=cstor_operator_deprovision.yml
bash ../Openshift-EE/utils/dump_cluster_state;
cd ..
bash Openshift-EE/utils/event_updater jobname:cleanup-cstor-operator $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:cleanup-cstor-operator jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 Openshift-EE/utils/result/result_update.py $job_id RZTG 11-cleanup "cleanup cstor-operator" $testResult $pipeline_id "$current_time" $commit_id $gittoken
if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6
else
  pod
fi