#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/7-csi-infra-setup/RZ25-csi-storage-policies/openebs-csi-sc node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

time="date"
current_time=$(eval $time)
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=GUGS
source ~/.profile
gittoken=$(echo "$github_token")

present_dir=$(pwd)
echo $present_dir

#pooling over previous job to complete
echo "***********Applying openebs-storage-clas********"
bash Openshift-EE/utils/pooling jobname:cstor-cspc-mirrored-pool
bash Openshift-EE/utils/e2e-cr jobname:cstor-csi-storage-policies jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

run_id="csi-sc";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=cstor-storage-policies metadata=${run_id})
echo $test_name

cd litmus
echo "Running the litmus test.."

cp providers/cstor-storage-policies/run_litmus_test.yml cstor-csi-sc.yaml

sed -i -e 's/value: cstor-sparse-pool/value: cstor-cspc-disk-pool/g' \
-e 's/value: spc/value: cspc/g' \
-e 's/app: cstor-storage-policy/app: cstor-csi-storage-policy/g' cstor-csi-sc.yaml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' cstor-csi-sc.yaml

cat cstor-csi-sc.yaml

bash ../Openshift-EE/utils/litmus_job_runner label='app:cstor-csi-storage-policy' job=cstor-csi-sc.yaml

echo "Dumping state of cluster post job run"; echo ""
bash ../Openshift-EE/utils/dump_cluster_state;

cd ..
bash Openshift-EE/utils/event_updater jobname:cstor-csi-storage-policies $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:cstor-csi-storage-policies jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult 

python3 Openshift-EE/utils/result/result_update.py $job_id RZ25 7-csi-infra-setup "Create K8s storage classes adhering the policies supported by OpenEBS" $testResult $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
