#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/VGEA-clone-during-snap-rebuild/clone-during-rebuild node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > clone-during-snap-rebuild-$job_id.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/clone-during-rebuild/g" -e"s/<job_id>/$job_id/g" clone-during-snap-rebuild-$job_id.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" clone-during-snap-rebuild-$job_id.yml
kubectl apply -f clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml

echo "*******Deploying Application****"
sleep 5
echo "      Application-Deployment: Pass" >> clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml
kubectl apply -f clone-during-snap-rebuild-$job_id.yml

echo "*******Generating load**********"
sleep 5
echo "      Application-Loadgen: Pass" >> clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml
kubectl apply -f clone-during-snap-rebuild-$job_id.yml

echo "*******Taking clone when during snap rebuild in progress************"
sleep 5
echo "      Clone-during-rebuild: Fail" >> clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml
kubectl apply -f clone-during-snap-rebuild-$job_id.yml

echo "*******Deprovisioning Application******"
sleep 5
echo "      Application-Deprovisioning: Pass" >> clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml
kubectl apply -f clone-during-snap-rebuild-$job_id.yml

current_time=$(eval $time)
sed -i -e "s/<test-finish>/$current_time/g" clone-during-snap-rebuild-$job_id.yml
sed -i -e "s/<test-result>/Fail/g" clone-during-snap-rebuild-$job_id.yml
sed -i -e "s/Running/Completed/g" clone-during-snap-rebuild-$job_id.yml
cat clone-during-snap-rebuild-$job_id.yml
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
