#!/bin/bash

pod() {
node_name=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port kubectl get nodes --no-headers | grep -v master | awk 'FNR==1 {print $1}')
echo $node_name
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port "kubectl taint nodes $node_name infra-aid-"

sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-jiva-csi-infra-setup/JCSI01-jiva-operator/jiva-operator node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"' '"'$JIVA_OPERATOR_RELEASE_BRANCH'"' '"'$COMMIT_ID'"' '"'$JIVA_OPERATOR_IMAGE'"' '"'$JIVA_CSI_DRIVER_IMAGE'"' '"provision"' '"'$RC_TAG'"' 
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=JCSI01
commit_id=$(echo $3)
releaseTag=$(echo $4)
release_branch=$(echo $5)
release_commit_id=$(echo $6)
jiva_operator_image=$(echo $7)
jiva_csi_driver_image=$(echo $8)
action=$(echo $9)
rc_tag=$(echo ${10})

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
bash Openshift-EE/utils/e2e-cr jobname:jiva-operator jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:jiva-operator jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

#################
## RUNNER MAIN ##
#################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-jiva-operator-provision metadata="")
echo $test_name
cd litmus

cp providers/jiva-csi-provisioner/run_litmus_test.yml jiva_operator.yml

export COMMIT_ID=$release_commit_id
export RC_TAG=$rc_tag
export JIVA_OPERATOR_IMAGE=$jiva_operator_image
export JIVA_CSI_DRIVER_IMAGE=$jiva_csi_driver_image
export ACTION=$action

wget https://raw.githubusercontent.com/openebs/e2e-infrastructure/master/env-update/env.py
python3 env.py -f jiva_operator.yml

sed -i -e "/name: OPENEBS_VERSION/{n;s/.*/          value: ${releaseTag}/g}" \
-e "/name: RELEASE_BRANCH/{n;s/.*/          value: ${release_branch}/g}" \
-e "/name: ACTION/{n;s/.*/          value: ${ACTION}/g}" jiva_operator.yml

cat jiva_operator.yml

bash ../Openshift-EE/utils/litmus_job_runner label='provider:jiva-operator' job=jiva_operator.yml
bash ../Openshift-EE/utils/dump_cluster_state;
cd ..
bash Openshift-EE/utils/event_updater jobname:jiva-operator $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the litmus result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:jiva-operator jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

python3 Openshift-EE/utils/result/result_update.py $job_id JCSI01 jiva-csi-infra-setup "install jiva-operator" $testResult $pipeline_id "$current_time" $commit_id $gittoken
if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5 $6 $7 $8 $9 ${10} ${11}
else
  pod
fi
