#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/PG1D-cstor-volume-istgt-kill/cstor-volume-istgt-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=PG1D

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:target-istgt-kill jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:target-istgt-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-istgt-kill metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_target_istgt_kill.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-istgt-kill/g' \
-e 's/app=busybox-sts/app=istgt-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-istgt-targetkill/g' \
-e 's/value: app-busybox-ns/value: istgt-kill/g' busybox_target_istgt_kill.yml
cat busybox_target_istgt_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-istgt-kill' job=busybox_target_istgt_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-istgt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="istgt-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_istgt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | istgt-kill                                       | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-istgt-kill             |
 | appLabel          | env    | app=busybox-sts                     | app=istgt-kill                                   | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: istgt-kill/g' \
-e 's/app=busybox-sts/app=istgt-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-istgt-kill/g' busybox_loadgen_istgt_kill.yml

cat busybox_loadgen_istgt_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_istgt_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-istgt-kill' job=busybox_loadgen_istgt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:target-istgt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

echo "*******Performing Cstor pool Management kill**********"

run_id="istgt";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-target-failure metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_failure/run_litmus_test.yml run_target_istgt_kill_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-istgt-targetkill/g' \
-e 's/name: target-failure/name: target-istgt-kill/g' \
-e 's/name: openebs-target-failure/name: openebs-target-istgt-failure/g' \
-e 's/target-zrepl-kill/target-kill/g' \
-e 's/cstor-volume-mgmt/cstor-istgt/g' \
-e 's/value: docker/value: cri-o/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=istgt-kill'\''/g' \
-e 's/value: app-percona-ns/value: istgt-kill/g' run_target_istgt_kill_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_target_istgt_kill_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_target_istgt_kill_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: targetistgtkilltest
' run_target_istgt_kill_test.yml

echo "Running the litmus test for Busybox Deployment Scaleup.."
cat run_target_istgt_kill_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-target-istgt-failure' job=run_target_istgt_kill_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-istgt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-istgt-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_istgt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | istgt-kill                                       | 
 | appLabel          | env    | app=busybox-sts                     | app=istgt-kill                                   |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-istgt-kill|
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: istgt-kill/g' \
-e 's/app=busybox-sts/app=istgt-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-istgt-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-istgt-kill/g' busybox_loadgen_deprovision_istgt_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_istgt_kill.yml

cat busybox_loadgen_deprovision_istgt_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-istgt-kill' job=busybox_loadgen_deprovision_istgt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-istgt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-istgt-kill metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_target_istgt_kill.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-istgt-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-istgt-kill/g' \
-e 's/app=busybox-sts/app=istgt-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-istgt-targetkill/g' \
-e 's/value: app-busybox-ns/value: istgt-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_target_istgt_kill.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_target_istgt_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-istgt-kill' job=deprovision_target_istgt_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-istgt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:target-istgt-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:target-istgt-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id PG1D 4-chaos "Induce chaos on cstor-target container(cstor-istgt) and check the behaviour" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
