#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/8PI6-pool-network-delay/pool-network-delay node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=8PI6
commit_id=$(echo $3)
releaseTag=$(echo $4)
time="date"
current_time=$(eval $time)
source ~/.profile
gittoken=$(echo "$github_token")
present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:pool-network-delay jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:pool-network-delay jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-pool-delay metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_pool_delay.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-pool-delay/g' \
-e 's/app=busybox-sts/app=pool-delay/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-pooldelay/g' \
-e 's/value: app-busybox-ns/value: pool-delay/g' busybox_pool_delay.yml
cat busybox_pool_delay.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-pool-delay' job=busybox_pool_delay.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce Delay in cstor pool pods" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="pool-network-delay";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_pool_network_delay.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | pool-delay                                       | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-pool-network-delay    |
 | appLabel          | env    | app=busybox-sts                     | app=pool-delay                                   | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: pool-delay/g' \
-e 's/app=busybox-sts/app=pool-delay/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-pool-network-delay/g' busybox_loadgen_pool_network_delay.yml

cat busybox_loadgen_pool_network_delay.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_pool_network_delay.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-pool-network-delay' job=busybox_loadgen_pool_network_delay.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce pool network delay and check if app pod recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################
# Performing network delay in cStor Pool

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-cstor-pool-network-delay metadata="")
echo $test_name

cd litmus
cp experiments/chaos/openebs_pool_network/run_litmus_test.yml run_pooldelay_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-pooldelay/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=pool-delay'\''/g' \
-e 's/value: '\''enable'\''/value: '\'""\''/g' \
-e 's/value: app-percona-ns/value: pool-delay/g' run_pooldelay_test.yml

echo "Running the litmus test for Busybox Deployment Scaleup.."
cat run_pooldelay_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-pool-network' job=run_pooldelay_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce Delay in cstor pool pods" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-pool-network-delay";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_pool_network_delay.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                                          |
  --------------------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | pool-delay                                                  | 
 | appLabel          | env    | app=busybox-sts                     | app=pool-delay                                              |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-pool-network-delay   |
 | action            | env    | provision                           | deprovision                                                 | 
  --------------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: pool-delay/g' \
-e 's/app=busybox-sts/app=pool-delay/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-pool-network delay/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-pool-network-delay/g' busybox_loadgen_deprovision_pool_network_delay.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_pool_network_delay.yml

cat busybox_loadgen_deprovision_pool_network_delay.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-pool-network-delay' job=busybox_loadgen_deprovision_pool_network_delay.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce pool network delay and check if app pod recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

# Deprovisioning Busybox Application

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-pool-delay metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_pool_delay.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-pool-delay/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-pool-delay/g' \
-e 's/app=busybox-sts/app=pool-delay/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-pooldelay/g' \
-e 's/value: app-busybox-ns/value: pool-delay/g' \
-e 's/value: provision/value: deprovision/g' deprovision_pool_delay.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_pool_delay.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-pool-delay' job=deprovision_pool_delay.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:pool-network-delay $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"
rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:pool-network-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce Delay in cstor pool pods" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:pool-network-delay jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id 8PI6 4-chaos "Induce Delay in cstor pool pods" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
