#!/bin/bash
set -x

pod() {
sshpass -p $pass_e2e ssh -o StrictHostKeyChecking=no $user_e2e@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/GitLab/stages/4-chaos/XMSV-gitlab-unicorn-failure/gitlab-unicorn-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=XMSV

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:unicorn-app-kill jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:unicorn-app-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

echo "*******Performing Application(UNICORN) Pod Chaos**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=application-pod-failure metadata="")
echo $test_name

cd litmus
cp experiments/chaos/app_pod_failure/run_litmus_test.yml appkill.yml

sed -i -e 's/app=jenkins-app/app=unicorn/g' \
-e 's/value: app-jenkins-ns/value: default/g' appkill.yml

echo "Running the litmus test for Gitlab-Unicorn Deployment application pod kill.."
cat appkill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:application-pod-failure' job=appkill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:unicorn-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
# python3 Openshift-EE/utils/result/result_update.py $job_id XMSV 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

gitlab_service=$(curl -k https://gitlab.litmuschaos.io)

if [ "$testResult" == "Pass" ] && [ "$?" == "0" ]; then
gitlab_test_result=Pass;
else
echo "Gitlab Service is Unreachable"
gitlab_test_result=Fail;
# python3 Openshift-EE/utils/result/result_update.py $job_id XMSV 4-chaos "Induce application pod failure and check if it is recovered successfully" $gitlab_test_result $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:unicorn-app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
# python3 Openshift-EE/utils/result/result_update.py $job_id XMSV 4-chaos "Induce application pod failure and check if it is recovered successfully" $gitlab_test_result $pipeline_id "$current_time" $commit_id $gittoken

}

if [ "$1" == "node" ];then
  node $2 $3 $4
else
  pod
fi
