#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-openshift && git checkout OpenEBS-base && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/QDLO-Data-Integrity/data-integrity node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=QDLO

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

sed -i "s/-<job_id>/ /g" Openshift-EE/utils/e2e-result.yml

bash Openshift-EE/utils/e2e-cr jobname:data-integrity jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:data-integrity jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

echo "*******Deploying Busybox-sts Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=fio-data-integrity metadata="")
echo $test_name
cd litmus
echo "Running the litmus test for Busybox Deployment.."
run_test=apps/fio/tests/data-integrity/run_litmus_test.yml
sed -i -e 's/value: openebs-standard/value: openebs-cstor-sparse/g' $run_test

cat $run_test

bash ../Openshift-EE/utils/litmus_job_runner label='app:fio-di-litmus' job=$run_test
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:data-integrity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:data-integrity jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass

}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi

