#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/stages/4-chaos/4CCO01-application-pod-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1) #Gitlab job id obtain from the gitlab env ($CI_JOB_ID).
pipeline_id=$(echo $2) # Gitlab pipeline id obtained from gitlab env ($CI_PIPELINE_ID).
commit_id=$(echo $3) #Gitlab commit id Obtained fron gilab env ($CI_COMMIT_SHA).
releaseTag=$(echo $4)
source ~/.profile
#github token to push the test result into github mayadata-io/e2e-openshift repository.
#This token is set as an env in ~/.profile in the test cluster.
#gittoken=$(echo "$github_token")
case_id=4CCO01  #test case ID.

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir
#Creating e2e custom resource result for the test.
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-app-kill jobphase:Waiting
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-app-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

################
# e2eBook 1 #
################

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-provision-csi-app-kill metadata="")
echo $test_name

cd cstor-operators/e2e-tests
echo "Running the e2e test for Busybox Deployment.."
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/deployers/run_e2e_test.yml busybox_csi_app_kill.yml

# Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | csi-app-kill                                     | 
 | e2e job label  | label  | app: busybox-e2e                 | app: deploy-busybox-app-kill                     |
 | appLabel          | env    | app=busybox                     | app=app-kill                                     | 
 | storage class     | env    | openebs-cstor-csi                | openebs-cstor-csi                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-appkill                               |
  ----------------------------------------------------------------------------------------------------------------------
EOF

oc adm policy add-scc-to-user anyuid system:serviceaccount:csi-app-kill:default

sed -i -e 's/app: busybox-e2e/app: deploy-busybox-csi-app-kill/g' \
-e 's/app=busybox/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: app-busybox-ns/value: csi-app-kill/g' busybox_csi_app_kill.yml
cat busybox_csi_app_kill.yml

# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:deploy-busybox-csi-app-kill' job=busybox_csi_app_kill.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-openshift-e2e/utils/event_updater jobname:csi-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 2 #
################

run_id="csi-app-kill";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd cstor-operators/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_csi_app_kill.yml

# Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | csi-app-kill                                         | 
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: busybox-liveness-app-kill              |
 | appLabel          | env    | app=busybox                     | app=app-kill                                     | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: csi-app-kill/g' \
-e 's/app=busybox/app=app-kill/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-csi-app-kill/g' busybox_loadgen_csi_app_kill.yml

cat busybox_loadgen_csi_app_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_csi_app_kill.yml

# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-csi-app-kill' job=busybox_loadgen_csi_app_kill.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
# Update the e2e event for the job.
bash openebs-openshift-e2e/utils/event_updater jobname:csi-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 3 #
################

# Performing Application Pod Chaos

run_id="csi-app-kill";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=application-pod-failure metadata=${run_id})
echo $test_name

cd cstor-operators/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/chaos/app_pod_failure/run_e2e_test.yml csi_app_kill.yml

sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: csi-app-kill/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=app-kill'\''/}' \
-e '/name: CONTAINER_RUNTIME/{n;s/.*/            value: cri-o/}' \
-e '/name: DEPLOY_TYPE/{n;s/.*/            value: deployment/}' \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' csi_app_kill.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: appkill
' csi_app_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' csi_app_kill.yml

echo "Running the e2e test for Busybox Deployment application pod kill.."
cat csi_app_kill.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='name:application-pod-failure' job=csi_app_kill.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$?" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 4 #
################

run_id="deprovision-csi-app-kill";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd cstor-operators/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_deprovision_csi_app_kill.yml

# Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | csi-app-kill                                         | 
 | appLabel          | env    | app=busybox                     | app=app-kill                                     |
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: busybox-liveness-deprovision-app-kill  |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: csi-app-kill/g' \
-e 's/app=busybox/app=app-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-deprovision-csi-app-kill/g' busybox_loadgen_deprovision_csi_app_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_csi_app_kill.yml

cat busybox_loadgen_deprovision_csi_app_kill.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='liveness:busybox-liveness-deprovision-csi-app-kill' job=busybox_loadgen_deprovision_csi_app_kill.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail "$current_time" $#gittoken
exit 1;
fi

################
# e2eBook 5 #
################

test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=busybox-deprovision-csi-app-kill metadata="")
echo $test_name

cd cstor-operators/e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/deployers/run_e2e_test.yml deprovision_csi_app_kill.yml

# Update the environmental variables in e2e job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | csi-app-kill                                         | 
 | e2e job label  | label  | app: busybox-e2e                 | app: busybox-deprovision-app-kill                |
 | appLabel          | env    | app=busybox                     | app=app-kill                                     | 
 | storage class     | env    | openebs-cstor-csi                | openebs-cstor-csi                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-appkill                               |
 | action            | env    | provision                           | deprovison                                       |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: e2e-busybox-deploy/generateName: busybox-deprovision-csi-app-kill/g' \
-e 's/app: busybox-e2e/app: busybox-deprovision-csi-app-kill/g' \
-e 's/app=busybox/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi/g' \
-e 's/value: app-busybox-ns/value: csi-app-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_csi_app_kill.yml

# Running the e2e test for Busybox Deprovision
cat deprovision_csi_app_kill.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:busybox-deprovision-csi-app-kill' job=deprovision_csi_app_kill.yml
cd ../..
# Get the cluster state Once the e2e jobs completed.
bash openebs-openshift-e2e/utils/dump_cluster_state;
bash openebs-openshift-e2e/utils/event_updater jobname:csi-app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Fail "$current_time" $#gittoken
exit 1;
fi

bash openebs-openshift-e2e/utils/e2e-cr jobname:csi-app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
#python3 openebs-openshift-e2e/utils/result/result_update.py $job_id 4CCO01 4-chaos "Induce application pod failure and check if it is recovered successfully" Pass "$current_time" $#gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
