#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-openshift && git checkout release-branch && bash Openshift-EE/pipelines/OpenEBS-base/stages/6-cleanup/4SMQ-cluster-cleanup/cluster-cleanup node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)

git clone https://github.com/mayadata-io/litmus.git
cd litmus

# Replace the VM IP In csv file
sed -i -e 's/10.12.22.10/10.34.1.28/g' \
-e 's/10.12.22.11/10.34.1.29/g' \
-e 's/10.12.22.12/10.34.1.30/g' \
-e 's/10.12.22.13/10.34.1.31/g' k8s/on-prem/openshift-installer/ip.csv

sed -i '/10.34.1.31/a \
10.34.1.32 \
10.34.1.33
' k8s/on-prem/openshift-installer/ip.csv

#Replace the Vm names in csv file
sed -i -e 's/auto1/oc-master-4.2/g' \
-e 's/auto2/oc-worker1-4.2/g' \
-e 's/auto3/oc-worker2-4.2/g' \
-e 's/auto4/oc-worker3-4.2/g' k8s/on-prem/openshift-installer/vm_name.csv

sed -i '/oc-worker3-4.2/a \
oc-worker4-4.2 \
oc-worker5-4.2
' k8s/on-prem/openshift-installer/vm_name.csv

#Replace the snapshot name and exp ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "cauto"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.23.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv

#Removimg e2e openshift test repo
cd  && rm -rf e2e-openshift && rm -rf infra
cd /home/devuser/go/src/github.com/openebs && rm -rf maya
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
