#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'cd e2e-openshift && git checkout OpenEBS-base && bash Openshift-EE/pipelines/OpenEBS-base/stages/6-cleanup/4SMQ-cluster-cleanup/cluster-cleanup node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)

git clone https://github.com/openebs/litmus.git
cd litmus

# Replace the VM IP In csv file
sed -i -e 's/10.12.22.10/10.23.1.10/g' \
-e 's/10.12.22.11/10.23.1.11/g' \
-e 's/10.12.22.12/10.23.1.12/g' \
-e 's/10.12.22.13/10.23.1.13/g' k8s/on-prem/openshift-installer/ip.csv

sed -i '/10.23.1.13/a \
10.23.1.14 \
10.23.1.15
' k8s/on-prem/openshift-installer/ip.csv

#Replace the Vm names in csv file
sed -i -e 's/auto1/AutoCluster-M/g' \
-e 's/auto2/AutoCluster-N1/g' \
-e 's/auto3/AutoCluster-N2/g' \
-e 's/auto4/AutoCluster-N3/g' k8s/on-prem/openshift-installer/vm_name.csv

sed -i '/AutoCluster-N3/a \
AutoCluster-N4 \
AutoCluster-N5
' k8s/on-prem/openshift-installer/vm_name.csv

#Replace the snapshot name and exp ip in vars
sed -i -e 's/snapshot_name: "oc-cluster"/snapshot_name: "cauto"/g' \
-e 's/esx_ip: "10.12.1.1"/esx_ip: "10.23.1.1"/g' k8s/on-prem/openshift-installer/vars.yml

ansible-playbook k8s/on-prem/openshift-installer/revert_cluster_state.yml -vv

#Removimg e2e openshift test repo
cd  && rm -rf e2e-openshift && rm -rf infra
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
