#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/2HXA-cstor-volume-mgmt-kill/cstor-volume-mgmt-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")
case_id=2HXA

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:target-mgmt-kill jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:target-mgmt-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"


################
# LitmusBook 1 #
################

# Deploying Busybox Application

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-mgmt-kill metadata="")
echo $test_name

cd litmus
# Running the litmus test for Busybox Deployment

cp apps/busybox/deployers/run_litmus_test.yml busybox_target_mgmt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | mgmt-kill                                        | 
 | Litmus job label  | label  | app: busybox-litmus                 | app: deploy-busybox-target-mgmt-kill             |
 | appLabel          | env    | app=busybox-sts                     | app=target-mgmt-kill                             | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-mgmt-targetkill                       |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-target-mgmt-kill/g' \
-e 's/app=busybox-sts/app=target-mgmt-kill/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-mgmt-targetkill/g' \
-e 's/value: app-busybox-ns/value: mgmt-kill/g' busybox_target_mgmt_kill.yml
cat busybox_target_mgmt_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-target-mgmt-kill' job=busybox_target_mgmt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:target-mgmt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 2 #
################

run_id="mgmt-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_mgmt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | mgmt-kill                                        | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-mgmt-kill             |
 | appLabel          | env    | app=busybox-sts                     | app=target-mgmt-kill                             | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: mgmt-kill/g' \
-e 's/app=busybox-sts/app=target-mgmt-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-mgmt-kill/g' busybox_loadgen_mgmt_kill.yml
cat busybox_loadgen_mgmt_kill.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_mgmt_kill.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-mgmt-kill' job=busybox_loadgen_mgmt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:target-mgmt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

# Performing Cstor volume Management kill

run_id="mgmt";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-target-failure metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_failure/run_litmus_test.yml run_target_mgmt_kill_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-mgmt-targetkill/g' \
-e 's/name: target-failure/name: target-mgmt-kill/g' \
-e 's/name: openebs-target-failure/name: openebs-target-mgmt-failure/g' \
-e 's/value: docker/value: cri-o/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=target-mgmt-kill'\''/g' \
-e 's/value: app-percona-ns/value: mgmt-kill/g' run_target_mgmt_kill_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_target_mgmt_kill_test.yml

## Replace the value of DATA_PERSISTENCE with application name in litmus experiment. 
sed -i '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_target_mgmt_kill_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: targetmgmtkilltest
' run_target_mgmt_kill_test.yml

# Running the litmus test for Busybox Deployment Scaleup
cat run_target_mgmt_kill_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-target-mgmt-failure' job=run_target_mgmt_kill_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-mgmt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Fail $pipeline_id "$current_time" $commit_id $gittoken

exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-mgmt-kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_mgmt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | mgmt-kill                                        | 
 | appLabel          | env    | app=busybox-sts                     | app=target-mgmt-kill                             |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-mgmt-kill |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: mgmt-kill/g' \
-e 's/app=busybox-sts/app=target-mgmt-kill/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-mgmt-kill/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-mgmt-kill/g' busybox_loadgen_deprovision_mgmt_kill.yml


sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_mgmt_kill.yml

cat busybox_loadgen_deprovision_app_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-mgmt-kill' job=busybox_loadgen_deprovision_mgmt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-mgmt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

# Deprovisioning Busybox Application

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-mgmt-kill metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_target_mgmt_kill.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | mgmt-kill                                        | 
 | Litmus job label  | label  | app: busybox-litmus                 | app: busybox-deprovision-mgmt-kill               |
 | appLabel          | env    | app=busybox-sts                     | app=target-mgmt-kill                             | 
 | storage class     | env    | openebs-cstor-sparse                | openebs-cstor-disk                               |
 | deploy type       | env    | statefulset                         | deployment                                       |
 | appPVC            | env    | openebs-busybox                     | openebs-bb-mgmt-targetkill                       |
 | action            | env    | provision                           | deprovison                                       |
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-mgmt-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-mgmt-kill/g' \
-e 's/app=busybox-sts/app=target-mgmt-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-mgmt-targetkill/g' \
-e 's/value: app-busybox-ns/value: mgmt-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_target_mgmt_kill.yml

# Running the litmus test for Busybox Deprovision
cat deprovision_target_mgmt_kill.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-mgmt-kill' job=deprovision_target_mgmt_kill.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-mgmt-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
# Update result of the test case in github mayadata-io/e2e-openshift repository

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:target-mgmt-kill jobphase:Completed end_time:"$current_time" test_result:Pass jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:target-mgmt-kill jobphase:Completed end_time:"$current_time" test_result:Pass jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id 2HXA 4-chaos "Induce failure on cstor-volume-mgmt container in cstor-pool pod and check if it doesn't affect the application availability" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
