#!/bin/bash
set -x


pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/VZPY-target-kill/target-kill node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo $job_id
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > volume-kill-result.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/volume-kill/g" -e"s/<job_id>/$job_id/g" volume-kill-result.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" volume-kill-result.yml
kubectl apply -f volume-kill-result.yml
cat volume-kill-result.yml

echo "*******Deploying Application****"
sleep 5
echo "      Application-Deployment: Pass" >> volume-kill-result.yml
cat volume-kill-result.yml
kubectl apply -f volume-kill-result.yml

echo "*******Generating load**********"
sleep 5
echo "      Application-Loadgen: Pass" >> volume-kill-result.yml
cat volume-kill-result.yml
kubectl apply -f volume-kill-result.yml

echo "*******Killing volume************"
sleep 5
echo "      volume-kill: Fail" >> volume-kill-result.yml
cat volume-kill-result.yml
kubectl apply -f volume-kill-result.yml

echo "*******Deprovisioning Application******"
sleep 5
echo "      Application-Deprovisioning: Pass" >> volume-kill-result.yml
cat volume-kill-result.yml
kubectl apply -f volume-kill-result.yml

current_time=$(eval $time)
sed -i -e "s/<test-finish>/$current_time/g" volume-kill-result.yml
sed -i -e "s/<test-result>/Fail/g" volume-kill-result.yml
cat volume-kill-result.yml
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
