## Define the stages & order of execution

stages:
  - CLUSTER-SETUP
  - OPENEBS-SETUP
  - FUNCTIONAL
  - CHAOS
  - CLEANUP

HUNE-OpenShift-3.10:
  image: openebs/openshift-ci:latest
  stage: CLUSTER-SETUP
  script:     
    - chmod 755 ./Openshift-EE/pipelines/ElasticSearch/stages/1-cluster-setup/HUNE-cluster-state/cluster-state
    - ./Openshift-EE/pipelines/ElasticSearch/stages/1-cluster-setup/HUNE-cluster-state/cluster-state

CRGI-OpenEBS:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/CRGI-openebs-deploy/deploy-openebs
    - ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/CRGI-openebs-deploy/deploy-openebs

12PS-OpenEBS-POLICIES:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/12PS-storage-policies/openebs-sc
    - ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/12PS-storage-policies/openebs-sc
  
2RWJ-CSTOR-POOL:
  image: openebs/openshift-ci:latest
  stage: OPENEBS-SETUP
  script:
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/2RWJ-create-striped-pool/create-pool
    - ./Openshift-EE/pipelines/ElasticSearch/stages/2-setup/2RWJ-create-striped-pool/create-pool
    
.func_test_template:
  image: openebs/openshift-ci:latest
  stage: FUNCTIONAL
  when: always
  dependencies:
    - K9YC-OpenEBS
     
# 9AKX-Create-Snapshot:
#   extends: .func_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/9AKX-snapshot/snapshot
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/9AKX-snapshot/snapshot

# ZK9B-Create-Clone:
#   extends: .func_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/ZK9B-snapshot-clone/snapshot-clone
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/ZK9B-snapshot-clone/snapshot-clone

#       #5O5V-Parent-Vol-Delete:
#       #  extends: .func_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/5O5V-Clone-parent-vol-delete/clone-parent-vol-delete
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/5O5V-Clone-parent-vol-delete/clone-parent-vol-delete

# JAIP-STS-App-Target-Affinity:
#   extends: .func_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/JAIP-STS-App-Target-Affinity/sts-app-target-affinity
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/JAIP-STS-App-Target-Affinity/sts-app-target-affinity

#       #ENBK-App-Upgrade:
#       #  extends: .func_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/ENBK-Application-Upgrade/application-upgrade
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/ENBK-Application-Upgrade/application-upgrade


5Q19-Elasticsearch-Provision:
  extends: .func_test_template
  script: 	  script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/5Q19-deploy-elasticsearch/elasticsearch-provision
    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/5Q19-deploy-elasticsearch/elasticsearch-provision


86TL-App-Scaleup:
  extends: .func_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/86TL-App-replica-scaleup/app-replica-scaleup
    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/86TL-App-replica-scaleup/app-replica-scaleup

      #4E0O-Storage-Scaleup:
      #  extends: .func_test_template
      #  script: 
      #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/4E0O-Storage-Volume-scaleup/storage-volume-scaleup
      #    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/4E0O-Storage-Volume-scaleup/storage-volume-scaleup

      #GV2D-Storage-Upgrade:
      #  extends: .func_test_template
      #  script: 
      #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/GV2D-Storage-volume-upgrade/storage-volume-upgrade
      #    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/GV2D-Storage-volume-upgrade/storage-volume-upgrade

# 4ZWU-STS-Vol-Distribute:
#   extends: .func_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/4ZWU-STS-Volume-Distribution/volume-distribution
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/4ZWU-STS-Volume-Distribution/volume-distribution

# QDLO-Data-integrity:
#   extends: .func_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/QDLO-Data-Integrity/data-integrity
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/QDLO-Data-Integrity/data-integrity

# OBS2-Memory-Usage:
#   extends: .func_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/OBS2-Memory-Consumption/memory-consumption
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/OBS2-Memory-Consumption/memory-consumption

#       #29O5-Fill-Volume:
#       #  extends: .func_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/29O5-Volume-Capacity/volume-capacity
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/29O5-Volume-Capacity/volume-capacity

# UH9A-Jiva-Data-Integrity:
#   extends: .func_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/UH9A-Jiva-Data-Integrity/data-integrity
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/UH9A-Jiva-Data-Integrity/data-integrity

# KUL9-Jiva-App-Scaleup:
#   extends: .func_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/KUL9-Jiva-sts-App-replica-scaleup/app-replica-scaleup
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/KUL9-Jiva-sts-App-replica-scaleup/app-replica-scaleup

# UURF-Jiva-STS-App-Target-Affinity:
#   extends: .func_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/UURF-Jiva-sts-App-Target-Affinity/sts-app-target-affinity
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/UURF-Jiva-sts-App-Target-Affinity/sts-app-target-affinity

# SN3A-Jiva-Memory-Consumption:
#   extends: .func_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/SN3A-Jiva-Memory-Consumption/memory-consumption
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/3-functional/SN3A-Jiva-Memory-Consumption/memory-consumption      

.chaos_test_template:
  image: openebs/openshift-ci:latest
  stage: CHAOS
  when: always
  dependencies:
    - K9YC-OpenEBS

  
N4NK-Openebs-Pool-Failure:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/N4NK-openebs-pool-failure/openebs_pool_failure
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/N4NK-opeenbs-pool-failure/openebs_pool_failure


3K0C-Openebs-Target-Network-Delay:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/3K0C-openebs-target-network-delay/openebs_target_network_delay
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/3K0C-openebs-target-network-delay/openebs_target_network_delay


2YLI-Cstor-Volume-Istgt-Kill:
  extends: .chaos_test_template
  script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/2YLI-cstor-volume-istgt-kill/cstor-volume-istgt-kill
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/2YLI-cstor-volume-istgt-kill/cstor-volume-istgt-kill

37B3-Openebs-Target-Tailure:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/37B3-openebs-target-failure/openebs-target-failure
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/37B3-openebs-target-failure/openebs-target-failure
    
401P-Elasticsearch-Pod-Failure:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/401P-elasticsearch-pod-failure/elasticsearch-pod-failure
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/401P-elasticsearch-pod-failure/elasticsearch-pod-failure

638K-Cstor-Pool-Kill:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/638K-cstor-pool-kill/cstor-pool-kill
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/638K-cstor-pool-kill/cstor-pool-kill

E16S-Cstor-Volume-Mgmt-Kill:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/638K-cstor-pool-kill/cstor-pool-kill
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/638K-cstor-pool-kill/cstor-pool-kill


II1Z-Pool-Network-Delay:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/II1Z-pool-network-delay/pool-network-delay
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/II1Z-pool-network-delay/pool-network-delay

IOWW-Cstor-Pool-Delete:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/IOWW-cstor-pool-delete/cstor-pool-delete
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/IOWW-cstor-pool-delete/cstor-pool-delete


LY12-Target-Network-Delay:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/LY12-target-network-delay/target-network-delay
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/LY12-target-network-delay/target-network-delay


PMIJ-Openebs-Node-Service-Failure:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/PMIJ-openebs-node-service-failure/openebs-node-service-failure
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/PMIJ-openebs-node-service-failure/openebs-node-service-failure



QQ9F-Pool-Network-Loss:
   extends: .chaos_test_template
   script: 
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QQ9F-pool-network-loss/pool-network-loss
    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QQ9F-pool-network-loss/pool-network-loss


# PG1D-cStor-istgt-Kill:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/PG1D-cstor-volume-istgt-kill/cstor-volume-istgt-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/PG1D-cstor-volume-istgt-kill/cstor-volume-istgt-kill

# KBM1-cStor-Pool-Kill:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/KBM1-cstor-pool-kill/cstor-pool-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/KBM1-cstor-pool-kill/cstor-pool-kill

# 72WM-cStor-Pool-Delete:
#   extends: .chaos_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/72WM-cstor-pool-delete/cstor-pool-delete
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/72WM-cstor-pool-delete/cstor-pool-delete

# VZPY-cStor-target-kill:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VZPY-target-kill/target-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VZPY-target-kill/target-kill

# GFL0-Target-n/w-Delay:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/GFL0-target-network-delay/target-network-delay
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/GFL0-target-network-delay/target-network-delay

# QCA4-Target-n/w-Loss:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QCA4-target-network-loss/target-network-loss
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QCA4-target-network-loss/target-network-loss

# 340W-Snap-Rebuild-single-replica:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/340W-snap-rebuild-single-rep/snap-rebuild-single-rep
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/340W-snap-rebuild-single-rep/snap-rebuild-single-rep

# QKFK-Snap-Rebuild-multiple-replica:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QKFK-snap-rebuild-multiple-rep/snap-rebuild-multiple-rep
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QKFK-snap-rebuild-multiple-rep/snap-rebuild-multiple-rep

#       #WQFI-Clone-Rebuild-before-snapshot-rebuild:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/WQFI-clone-pre-snap-rebuild/clone-pre-rebuild
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/WQFI-clone-pre-snap-rebuild/clone-pre-rebuild

#       #VGEA-Clone-Rebuild-during-snapshot-rebuild:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VGEA-clone-during-snap-rebuild/clone-during-rebuild
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VGEA-clone-during-snap-rebuild/clone-during-rebuild

# QURH-Clone-Rebuild-post-snapshot-rebuild:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QURH-clone-post-snap-rebuild/clone-post-rebuild
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/QURH-clone-post-snap-rebuild/clone-post-rebuild

#       #I9VM-Pool-n/w-Loss:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/I9VM-pool-network-loss/pool-network-loss
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/I9VM-pool-network-loss/pool-network-loss

#       #8PI6-Pool-n/w-Delay:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/8PI6-pool-network-delay/pool-network-delay
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/8PI6-pool-network-delay/pool-network-delay

# 2HXA-volume-mgmt-kill:
#   extends: .chaos_test_template
#   script: 
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/2HXA-cstor-volume-mgmt-kill/cstor-volume-mgmt-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/2HXA-cstor-volume-mgmt-kill/cstor-volume-mgmt-kill

#       #RTOH-Kubelet-Crash:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/RTOH-kubelet-down/kubelet-down
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/RTOH-kubelet-down/kubelet-down

#       #DQKT-Node-Shutdown:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/DQKT-node-shutdown/node-shutdown
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/DQKT-node-shutdown/node-shutdown

#       #E92G-Docker-Crash:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/E92G-docker-down/docker-down
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/E92G-docker-down/docker-down

#       #ZCM2-Memory-pressure:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/ZCM2-memory-pressure/memory-pressure
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/ZCM2-memory-pressure/memory-pressure

#       #XUF7-CPU-Pressure:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/XUF7-cpu-pressure/cpu-pressure
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/XUF7-cpu-pressure/cpu-pressure

#       #TGZK-Drain-Node:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/TGZK-drain-node/drain-node
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/TGZK-drain-node/drain-node

#       #BF12-Evict-Node:
#       #  extends: .chaos_test_template
#       #  script: 
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/BF12-evict-node/evict-node
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/BF12-evict-node/evict-node

# AUZF-Jiva-App-Kill:
#   extends: .chaos_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/AUZF-Jiva-app-kill/jiva-app-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/AUZF-Jiva-app-kill/jiva-app-kill

# HOSN-Jiva-single-replica-failure:
#   extends: .chaos_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/HOSN-jiva-single-replica-failure/single-replica-failure
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/HOSN-jiva-single-replica-failure/single-replica-failure

# VO3D-Jiva-controller-kill:
#   extends: .chaos_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VO3D-jiva-controller-kill/controller-kill
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/VO3D-jiva-controller-kill/controller-kill

# TSXL-Jiva-controller-network-delay:
#   extends: .chaos_test_template
#   script:
#     - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/TSXL-Jiva-controller-network-delay/controller-network-delay
#     - ./Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/TSXL-Jiva-controller-network-delay/controller-network-delay

#       #GP95-openebs-Uninstall:
#       #  image: openebs/openshift-ci:latest
#       #  stage: CLEANUP
#       #  when: always
#       #  dependencies:
#       #    - K9YC-OpenEBS
#       #  script:
#       #    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/5-cleanup/GP95-openebs-cleanup/openebs-cleanup
#       #    - ./Openshift-EE/pipelines/ElasticSearch/stages/5-cleanup/GP95-openebs-cleanup/openebs-cleanup

638K-cluster-Delete:
  image: openebs/openshift-ci:latest
  stage: CLEANUP
  when: always
  dependencies:
    - HUNE-OpenShift-3.10
  script:
    - chmod 775 ./Openshift-EE/pipelines/ElasticSearch/stages/5-cleanup/638K-cluster-cleanup/cluster-cleanup
    - ./Openshift-EE/pipelines/ElasticSearch/stages/5-cleanup/638K-cluster-cleanup/cluster-cleanup
