#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/340W-snap-rebuild-single-rep/snap-rebuild-single-rep node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=340W

source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:snap-rebuild-single-rep jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:snap-rebuild-single-rep jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash Openshift-EE/utils/e2e-cr jobname:snap-rebuild-multiple-rep jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:clone-post-snap-rebuild jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:pool-delete jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:pool-kill jobphase:Waiting

################
# LitmusBook 1 #
################

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-snap-1rep metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_snap_1rep.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-snap-1rep/g' \
-e 's/app=busybox-sts/app=snap-1rep/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-snap-1rep/g' \
-e 's/value: app-busybox-ns/value: snap-1rep/g' busybox_snap_1rep.yml
cat busybox_snap_1rep.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-snap-1rep' job=busybox_snap_1rep.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:snap-rebuild-single-rep $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi
################
# LitmusBook 2 #
################

run_id="snap-1rep";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_snap_1rep.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | snap-1rep                                        | 
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-snap-1rep             |
 | appLabel          | env    | app=busybox-sts                     | app=snap-1rep                                    | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: snap-1rep/g' \
-e 's/app=busybox-sts/app=snap-1rep/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-snap-1rep/g' busybox_loadgen_snap_1rep.yml

cat busybox_loadgen_snap_1rep.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_snap_1rep.yml

# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-snap-1rep' job=busybox_loadgen_snap_1rep.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
# Update the e2e event for the job.
bash Openshift-EE/utils/event_updater jobname:snap-rebuild-single-rep $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 3 #
################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=snap-rebuild-single-rep metadata="")
echo $test_name

cd litmus
cp experiments/functional/snapshot_rebuild/snap_rebuild_single_rep/run_litmus_test.yml run_snap_1rep.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-bb-snap-1rep/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=snap-1rep'\''/g' \
-e 's/value: percona-cstor/value: snap-1rep/g' run_snap_1rep.yml

echo "Running the litmus test for Busybox Deployment snapshot rebuild.."
cat run_snap_1rep.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:k8s-snap-single-rep-rebuild' job=run_snap_1rep.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:snap-rebuild-single-rep $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 4 #
################

run_id="deprovision-snap-1rep";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd litmus
# copy the content of deployer run_litmus_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_litmus_test.yml busybox_loadgen_deprovision_snap_1rep.yml

# Update the environmental variables in litmus job spec.

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | snap-1rep                                        | 
 | appLabel          | env    | app=busybox-sts                     | app=snap-1rep                                    |
 | Litmus job label  | label  | liveness: litmus-busybox-liveness   | liveness: busybox-liveness-deprovision-snap-1rep |
 | action            | env    | provision                           | deprovision                                      | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: snap-1rep/g' \
-e 's/app=busybox-sts/app=snap-1rep/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/generateName: litmus-busybox-liveness/generateName: busybox-liveness-dep-snap-single-rep/g' \
-e 's/liveness: litmus-busybox-liveness/liveness: busybox-liveness-deprovision-snap-1rep/g' busybox_loadgen_deprovision_snap_1rep.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_deprovision_snap_1rep.yml

cat busybox_loadgen_deprovision_snap_1rep.yml
# Run the Litmus job and get the details of the litmus job from litmus_job_runner utils.
bash ../Openshift-EE/utils/litmus_job_runner label='liveness:busybox-liveness-deprovision-snap-1rep' job=busybox_loadgen_deprovision_snap_1rep.yml
cd ..
# Get the cluster state Once the litmus jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:snap-rebuild-single-rep $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)

# Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

################
# LitmusBook 5 #
################

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-snap-1rep metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_snap_1rep.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-snap-1rep/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-snap-1rep/g' \
-e 's/app=busybox-sts/app=snap-1rep/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-snap-1rep/g' \
-e 's/value: app-busybox-ns/value: snap-1rep/g' \
-e 's/value: provision/value: deprovision/g' deprovision_snap_1rep.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_snap_1rep.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-snap-1rep' job=deprovision_snap_1rep.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:snap-rebuild-single-rep $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)
# testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:snap-rebuild-single-rep jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:snap-rebuild-single-rep jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass

python3 Openshift-EE/utils/result/result_update.py $job_id 340W 4-chaos "Check if the snapshot can be rebuilt after loss and recovery of single replica" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
