#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -p $port -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/stages/2-infra-setup/2ICO03-create-cspc-mirror-pool node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=2ICO03
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
#gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

#pooling over previous job to complete
echo "*******Creating cstor-pool**************"
bash openebs-openshift-e2e/utils/pooling jobname:cstor-cspc-striped-pool
bash openebs-openshift-e2e/utils/e2e-cr jobname:cstor-cspc-mirrored-pool jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

run_id="mirrored";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=cstor-pool-provision metadata=${run_id})
echo $test_name
cd cstor-operators/e2e-tests

# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/cstor-operator/cspc-pool-provision/run_e2e_test.yml cspc_create_mirrored_pool.yml

#################
## RUNNER MAIN ##
#################

sed -i -e 's/cstor-cspc-pool-provision/cstor-cspc-mirror-pool-provision/g' \
-e 's/cstor-cspc-disk-pool/cstor-cspc-mirror-pool/g' \
-e 's/value: stripe/value: mirror/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-csi-sc/g' cspc_create_mirrored_pool.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' cspc_create_mirrored_pool.yml

cat cspc_create_mirrored_pool.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='app:cstor-cspc-mirror-pool-provision' job=cspc_create_mirrored_pool.yml
bash ../../openebs-openshift-e2e/utils/dump_cluster_state;
cd ../..
bash openebs-openshift-e2e/utils/event_updater jobname:cstor-cspc-mirrored-pool $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
#gittoken=$(echo "$github_token")
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-openshift-e2e/utils/e2e-cr jobname:cstor-cspc-mirrored-pool jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
