#!/bin/bash

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash openebs-openshift-e2e/stages/2-infra-setup/2IJO03-storage-policies node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=JCSI04
commit_id=$(echo $3)
releaseTag=$(echo $4)
source ~/.profile
gittoken=$(echo "$github_token")

time="date"
current_time=$(eval $time)

bash openebs-openshift-e2e/utils/pooling jobname:jiva-operator
bash openebs-openshift-e2e/utils/e2e-cr jobname:storage-policies jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"

run_id="jiva";test_name=$(bash openebs-openshift-e2e/utils/generate_test_name testcase=openebs-jiva-csi-sc-provision metadata=${run_id})
echo $test_name

cd jiva-operator/e2e-tests

# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp experiments/jiva-operator/jiva-csi-storage-policies/run_e2e_test.yml run_storage_policy.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_storage_policy.yml
            
#################
## RUNNER MAIN ##
#################
echo "Running the e2e test.."

cat run_storage_policy.yml

bash ../../openebs-openshift-e2e/utils/e2e_job_runner label='name:jiva-csi-sc' job=run_storage_policy.yml
bash ../../openebs-openshift-e2e/utils/dump_cluster_state;
cd ../..
bash openebs-openshift-e2e/utils/event_updater jobname:storage-policies $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

#################
## GET RESULT  ##
#################
rc_val=$(echo $?)

## Check the test status & result from the e2e result custom resource
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)

current_time=$(eval $time)
bash openebs-openshift-e2e/utils/e2e-cr jobname:storage-policies jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:$testResult

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
