#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout master && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/9AKX-snapshot/snapshot node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)
echo "*********Applying e2e-crd***********"
kubectl apply -f Openshift-EE/utils/e2e-crd.yml

echo "****Creating e2e-crd********"
cat Openshift-EE/utils/e2e-result.yml > snapshot-result-$job_id.yml
sed -i -e "s/<test-phase>/Running/g" -e "s/<test-name>/K8s-snapshot/g" -e"s/<job_id>/$job_id/g" snapshot-result-$job_id.yml

time="date"
current_time=$(eval $time)
sed -i -e "s/<test-init>/$current_time/g" -e "s/<openebs-id>/0.8.1/g" snapshot-result-$job_id.yml
kubectl apply -f snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml

echo "*******Deploying Application****"
sleep 5
echo "      Application-Deployment: Pass" >> snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml
kubectl apply -f snapshot-result-$job_id.yml

echo "*******Generating load**********"
sleep 5
echo "      Application-Loadgen: Pass" >> snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml
kubectl apply -f snapshot-result-$job_id.yml

echo "*******Taking Snapshot************"
sleep 5
echo "      Snapshot: Fail" >> snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml
kubectl apply -f snapshot-result-$job_id.yml

echo "*******Deprovisioning Application******"
sleep 5
echo "      Application-Deprovisioning: Pass" >> snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml
kubectl apply -f snapshot-result-$job_id.yml

current_time=$(eval $time)
sed -i -e "s/<test-finish>/$current_time/g" snapshot-result-$job_id.yml
sed -i -e "s/<test-result>/Fail/g" snapshot-result-$job_id.yml
sed -i -e "s/Running/Completed/g" snapshot-result-$job_id.yml
cat snapshot-result-$job_id.yml
}

#"$@"

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
