#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'git clone https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip 'cd e2e-openshift && git checkout OpenEBS-base && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/ZD8F-Sts-App-replica-scaleup/app-replica-scaleup node '"'$CI_JOB_ID'"''
}

node() {
job_id=$(echo $1)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

sed -i "s/-<job_id>/ /g" Openshift-EE/utils/e2e-result.yml

bash Openshift-EE/utils/e2e-cr jobname:app-replica-scaleup jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:app-replica-scaleup jobphase:Running init_time:"$current_time"

echo "*******Deploying Busybox-sts Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=litmus-busybox-deploy metadata="")
echo $test_name
cd litmus
echo "Running the litmus test for Busybox Deployment.."
run_test=litmus/apps/busybox/deployers/run_litmus_test.yml
cat $run_test
cd ..
bash Openshift-EE/utils/litmus_job_runner label='app:busybox-litmus' job=$run_test
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-replica-scaleup $test_name
if [ "$?" != "0" ]; then
exit 1;
fi

echo "*******Scaling Application replicas**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-replica-scale metadata="")
echo $test_name
cd litmus
sed -i -e 's/app: cassandra-scaleup-litmus/app: busybox-scaleup-litmus/g' \
-e 's/value: 'app=cassandra'/value: 'app=busybox-sts'/g' \
-e 's/value: app-cass-ns/value: app-busybox-ns/g' /apps/cassandra/functional/scale_replicas/run_litmus_test
echo "Running the litmus test for Busybox Deployment Scaleup.."
run_test=litmus/apps/cassandra/functional/scale_replicas/run_litmus_test.yml
cat $run_test
cd ..
bash Openshift-EE/utils/litmus_job_runner label='app:busybox-scaleup-litmus' job=$run_test
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-replica-scaleup $test_name
if [ "$?" != "0" ]; then
exit 1;
fi

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=litmus-busybox-deprovision metadata="")
echo $test_name
cd litmus
sed -i -e 's/generateName: litmus-busybox-deploy/generateName: litmus-busybox-deprovision/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-litmus/g' \
-e 's/value: provision/value: deprovision/g' apps/busybox/deployers/run_litmus_test.yml
echo "Running the litmus test for Busybox Deployment Scaleup.."
run_test=litmus/apps/busybox/deployers/run_litmus_test.yml
cat $run_test
cd ..
bash Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-litmus' job=$run_test
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-replica-scaleup $test_name

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:app-replica-scaleup jobphase:Completed end_time:"$current_time" test_result:Pass
}

if [ "$1" == "node" ];then
  node $2
else
  pod
fi
