#!/bin/bash
set -x

echo "***Checking the cluster is Engaged or not*"

state="sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ls | grep e2e-openshift'"
cluster_state=$(eval $state)

while [ "${cluster_state}" == "e2e-openshift" ]; do
  echo "***cluster is Engaged******"
  wait=1
  cluster_state=$(eval $state)
  sleep 30
done

if [ "$wait" == "1" ]; then
sleep 120
fi

echo "*************************Checking the Cluster's Health********************"

echo "Checking for the number of nodes in ready state*******************************"
ready_nodes=$(sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 kubectl get nodes | grep Ready | wc -l)

if [ "$ready_nodes" -eq 6 ]; then
echo "Number of nodes in ready state is $ready_nodes"
echo "******Cluster is in Healthy state****"
echo "*************Dumping cluster state********"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 kubectl get nodes
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 kubectl get pod --all-namespaces
else
echo "All nodes are not ready"
echo "******Cluster is in Unhealthy state*******"
exit;
fi

echo "********Disabling Selinux on nodes********"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ssh root@10.23.1.11 setenforce 0'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ssh root@10.23.1.12 setenforce 0'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ssh root@10.23.1.13 setenforce 0'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ssh root@10.23.1.14 setenforce 0'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p 1658 'ssh root@10.23.1.15 setenforce 0'
