#!/bin/bash


pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/3-functional/VZFL-App-Target-affinity/app-target-affinity node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"' '"'$RELEASE_TAG'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")
job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
releaseTag=$(echo $4)
case_id=VZFL

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:app-target-affinity jobphase:Waiting init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" openebs_version:"$releaseTag"
bash Openshift-EE/utils/e2e-cr jobname:app-target-affinity jobphase:Running


##Deploying Busybox-sts application

################
# e2eBook 1 #
################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-target-affinity metadata="")
echo $test_name

cd e2e-tests
cp apps/busybox/deployers/run_e2e_test.yml deploy_affinity_test.yml

: << EOF
  -------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                             |
  -------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=target-affinity                            |
 | pvcName           | env    | openebs-busybox                     | busybox-target-affinity                        | 
 | appNamespace      | env    | app-busybox-ns                      | target-affinity                                | 
 | storage clas      | env    | openebs-cstor-sparse                | openebs-cstor-disk                             |
 | e2e Job name   | name   | generateName: e2e-busybox-deploy | generateName: busybox-deploy-affinity          |
 | e2e job label  | label  | app: busybox-e2e                 | app: busybox-target-affinity                   |
  --------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/app: busybox-e2e/app: busybox-target-affinity/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=target-affinity'\''/g' \
-e 's/value: app-busybox-ns/value: target-affinity/g' \
-e 's/value: openebs-busybox/value: busybox-target-affinity/g' \
-e 's/generateName: e2e-busybox-deploy/generateName: busybox-deploy-affinity/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' deploy_affinity_test.yml

cat deploy_affinity_test.yml

bash ../Openshift-EE/utils/e2e_job_runner label='app:busybox-target-affinity' job=deploy_affinity_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-target-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deploying loadgen and liveness

#################
# e2eBook 2 #
################

run_id="app-tar";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml busybox_loadgen_app_target_affinity.yml

 # Update the environmental variables in e2e job spec.

 : << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-affinity                                  | 
 | appLabel          | env    | app=busybox-sts                     | app=target-affinity                              | 
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness:busybox-liveness-app-target-affinity    | 
  ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-affinity/g' \
-e 's/app=busybox-sts/app=target-affinity/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: busybox-liveness-app-target-affinity/g'  busybox_loadgen_app_target_affinity.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' busybox_loadgen_app_target_affinity.yml

cat busybox_loadgen_app_target_affinity.yml
 # Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../Openshift-EE/utils/e2e_job_runner label='liveness:busybox-liveness-app-target-affinity' job=busybox_loadgen_app_target_affinity.yml
cd ..
# Get the cluster state Once the e2e jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

echo "*******Checking Application and Target Pod Affinity **********"

################
# e2eBook 3 #
################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=app-target-affinity metadata="")
echo $test_name

cd e2e-tests
cp experiments/functional/app-target-affinity/run_e2e_test.yml run_affinity_test.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value                     | test specifc value                         |
  ---------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                           | app=target-affinity                        | 
 | appNamespace      | env    | app-busybox-ns                            | target-affinity                            | 
 | e2e Job name   | name   | generateName: e2e-app-target-affinity- | generateName: e2e-target-affinity-      |
  ---------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: app=busybox-sts/value: app=target-affinity/g' \
-e 's/generateName: e2e-app-target-affinity-/generateName: e2e-target-affinity-/g' \
-e 's/value: app-busybox-ns/value: target-affinity/g' run_affinity_test.yml

cat run_affinity_test.yml

bash ../Openshift-EE/utils/e2e_job_runner label='app:e2e-affinity' job=run_affinity_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-target-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deprovisioning loadgen and liveness 

################
# e2eBook 4 #
################

run_id="de-target";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-liveness metadata=${run_id})
echo $test_name

cd e2e-tests
# copy the content of deployer run_e2e_test.yml into a different file to update the test specific parameters.
cp apps/busybox/liveness/run_e2e_test.yml bb_loadgen_deprovision_app_target_affinity.yml

 # Update the environmental variables in e2e job spec.

 : << EOF
  ---------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                               |
  ---------------------------------------------------------------------------------------------------------------------|
 | appNamespace      | env    | app-busybox-ns                      | target-affinity                                  | 
 | action            | env    | provision                           | deprovision                                      | 
 | appLabel          | env    | app=busybox-sts                     | app=target-affinity                              | 
 | e2e job label  | label  | liveness: e2e-busybox-liveness   | liveness: bb-liveness-deprovision-app-target-affinity |
 ----------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/value: app-busybox-ns/value: target-affinity/g' \
-e 's/value: provision/value: deprovision/g' \
-e 's/app=busybox-sts/app=target-affinity/g' \
-e 's/generateName: e2e-busybox-liveness/generateName: busybox-liveness-dep-app-target-affinity/g' \
-e 's/liveness: e2e-busybox-liveness/liveness: bb-liveness-deprovision-app-target-affinity/g' bb_loadgen_deprovision_app_target_affinity.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' bb_loadgen_deprovision_app_target_affinity.yml

cat bb_loadgen_deprovision_app_target_affinity.yml
# Run the e2e job and get the details of the e2e job from e2e_job_runner utils.
bash ../Openshift-EE/utils/e2e_job_runner label='liveness:bb-liveness-deprovision-app-target-affinity' job=bb_loadgen_deprovision_app_target_affinity.yml
cd ..
# Get the cluster state Once the e2e jobs completed.
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:sts-app-target-affinity-jiva $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

 rc_val=$(echo $?)

 # Update result of the test case in github mayadata-io/e2e-openshift repository.
if [ "$rc_val" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

##Deprovisioning Busybox Application

################
# e2eBook 5 #
################

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-target-affinity metadata="")
echo $test_name

cd e2e-tests
cp apps/busybox/deployers/run_e2e_test.yml deprovision_affinity.yml

: << EOF
  --------------------------------------------------------------------------------------------------------------------------
 | specAttribute     | kind   |         default value               | test specifc value                                   |
  -------------------------------------------------------------------------------------------------------------------------|
 | appLabel          | env    | app=busybox-sts                     | app=target-affinity                                  |
 | pvcName           | env    | openebs-busybox                     | busybox-target-affinity                              | 
 | appNamespace      | env    | app-busybox-ns                      | arget-affinity                                       | 
 | storage clas      | env    | openebs-cstor-sparse                | openebs-cstor-disk                                   |
 | Action            | env    | value: provision                    | value: deprovision                                   |
 | e2e Job name   | name   | generateName: e2e-busybox-deploy | generateName: busybox-deprovision-target-affinity    |
 | e2e job label  | label  | app: busybox-e2e                 | app: busybox-deprovision-affinity                    |
  -------------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e 's/generateName: e2e-busybox-deploy/generateName: busybox-deprovision-sts-target-affinity/g' \
-e 's/app: busybox-e2e/app: busybox-deprovision-affinity/g' \
-e 's/imagePullPolicy: Always/imagePullPolicy: IfNotPresent/g' \
-e 's/value: '\''app=busybox-sts'\''/value: '\''app=target-affinity'\''/g' \
-e 's/value: app-busybox-ns/value: target-affinity/g' \
-e 's/value: openebs-busybox/value: busybox-target-affinity/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: provision/value: deprovision/g' deprovision_affinity.yml

cat deprovision_affinity.yml

bash ../Openshift-EE/utils/e2e_job_runner label='app:busybox-deprovision-affinity' job=deprovision_affinity.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-target-affinity $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
current_time=$(eval $time)

# testResult=$(kubectl get e2eresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
if [ "$rc_val" != "0" ]; then
bash Openshift-EE/utils/e2e-cr jobname:app-target-affinity  jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Fail
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi

bash Openshift-EE/utils/e2e-cr jobname:app-target-affinity  jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" testcaseid:"$case_id" openebs_version:"$releaseTag" test_result:Pass
python3 Openshift-EE/utils/result/result_update.py $job_id VZFL 3-functional "Checking Application and target scheduled on same Node" Pass $pipeline_id "$current_time" $commit_id $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi
}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi
