#!/bin/bash
set -x

pod() {
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/ElasticSearch/stages/4-chaos/PMIJ-target-kill/target-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {
source ~/.profile
gittoken=$(echo "$github_token")

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)
case_id=PMIJ

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/pooling jobname:target-loss 
bash Openshift-EE/utils/e2e-cr jobname:target-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

# Performing target failure

################
# LitmusBook 3 #
################

run_id="kill";test_name=$(bash Openshift-EE/utils/generate_test_name testcase=openebs-target-failure metadata=${run_id})
echo $test_name

cd litmus
cp experiments/chaos/openebs_target_failure/run_litmus_test.yml run_targetkill_test.yml

: << EOF
  ---------------------------------------------------------------------------------------------------------------------    
 | specAttribute       | kind   |         default value                 | test specifc value                          |
  --------------------------------------------------------------------------------------------------------------------|
 | appPVC              | env    | percona-mysql-claim                   | openebs-esearch-elasticsearch-logging-0     |
 | litmus job label    | label  | openebs-target-failure                | openebs-target-kill                         |
 | appLabel            | label  | name=percona                          | app=elasticsearch                           |
 | livenessAppLabel    | label  |  ""                                   | liveness=elasticsearch-liveness             |
 | livenessAppNamespace| env    |  ""                                   | app-esearch-ns                              |
 | appNamespace        | env    | app-percona-ns                        | app-esearch-ns                              |
  ---------------------------------------------------------------------------------------------------------------------
EOF

sed -i -e  's/value: percona-mysql-claim/value: openebs-esearch-elasticsearch-logging-0/g' \
-e 's/name: openebs-target-failure/name: openebs-target-kill/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=elasticsearch'\''/g' \
-e '/name: LIVENESS_APP_LABEL/!b;n;c\            \ value: "liveness=elasticsearch-liveness"' \
-e '/name: LIVENESS_APP_NAMESPACE/!b;n;c\            \ value: "app-esearch-ns"' \
-e 's/value: app-percona-ns/value: app-esearch-ns/g' run_targetkill_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_targetkill_test.yml

cat run_targetkill_test.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:openebs-target-kill' job=run_targetkill_test.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
python3 Openshift-EE/utils/result/result_update.py $job_id PMIJ 4-chaos "Induce failure on cstor-target pod and check if it gets scheduled immediately and the application is available" Fail $pipeline_id "$current_time" $commit_id $gittoken
exit 1;
fi
