#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/5-chaos/bb-target-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)


time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

# echo "Setting up test dependencies.."   
# ${utils_path}/setup_dependencies e2e-test

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:bb-target-nw-delay jobphase:Waiting
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:bb-target-kill jobphase:Waiting
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:bb-target-kill jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

## Performing target failure

run_id="cstor-kill";test_name=$(bash script/utils/generate_test_name testcase=openebs-target-failure metadata=${run_id})
echo $test_name

git clone https://github.com/openebs/cstor-operators.git
cd  cstor-operators/e2e-tests

kubectl apply -f hack/rbac.yaml
kubectl apply -f hack/crds.yaml

cp experiments/chaos/openebs_target_failure/run_e2e_test.yml run_target_kill_test.yml

sed -i -e 's/value: percona-mysql-claim/value: openebs-busybox/g' \
-e 's/value: '\''name=percona'\''/value: '\''app=busybox-sts'\''/g' \
-e 's/target-zrepl-kill/target-delete/g' \
-e 's/name: target-failure/name: target-kill-configmap/g' \
-e 's/value: app-percona-ns/value: bb-cstor-deployment/g' run_target_kill_test.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' run_target_kill_test.yml


sed -i -e '/name: APP_NAMESPACE/{n;s/.*/            value: bb-cstor-deployment/}' \
-e '/name: APP_LABEL/{n;s/.*/            value: '\''app=busybox'\''/}' \
-e '/name: CONTAINER_RUNTIME/{n;s/.*/            value: docker/}' \
-e '/name: DEPLOY_TYPE/{n;s/.*/            value: deployment/}' \
-e '/name: TARGET_CONTAINER/{n;s/.*/            value: ""/}' \
-e "/name: TARGET_AFFINITY_CHECK/{n;s/value: 'enable'/value: 'disable'/g}" \
-e '/name: DATA_PERSISTENCE/{n;s/.*/            value: busybox/}' run_target_kill_test.yml

## Insert the set of variables for busybox data consistency util into configmap spec.
sed -i '/parameters.yml: |/a \
    blocksize: 4k\
    blockcount: 1024\
    testfile: targetkilltest
' run_target_kill_test.yml

echo "Running the e2e test for Busybox Deployment Scaleup.."
cat run_target_kill_test.yml

bash ../../openebs-openshift-e2e/script/utils/e2e_job_runner label='name:openebs-target-failure' job=run_target_kill_test.yml
cd ../..
bash script/utils/dump_cluster_state;
bash script/utils/event_updater jobname:bb-target-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:bb-target-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:bb-target-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass

if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi