#!/bin/bash

pod() {
mkdir -p /root/.ssh
touch /root/.ssh/id_rsa
echo "$SSH_KEYS" > /root/.ssh/id_rsa
chmod 600 /root/.ssh/id_rsa
ssh -o StrictHostKeyChecking=no $user@$ip -i /root/.ssh/id_rsa 'cd e2e-openshift && bash openebs-openshift-e2e/script/5-chaos/percona-deployment-cstor node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"' '"'$CI_COMMIT_SHA'"'
}

node() {

job_id=$(echo $1)
pipeline_id=$(echo $2)
commit_id=$(echo $3)

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-cstor jobphase:Waiting
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-cstor jobphase:Running init_time:"$current_time" job_id:"$job_id" pipeline_id:"$pipeline_id" openebs_version:"$releaseTag"

## Deploying percona application...

run_id="cstor";test_name=$(bash openebs-openshift-e2e/script/utils/generate_test_name testcase=percona-deployment metadata=${run_id})
echo $test_name

git clone https://github.com/openebs/cstor-operators
cd cstor-operators/e2e-tests
echo "Running the e2e test for percona Deployment..."
cp apps/percona/deployers/run_e2e_test.yml percona_cstor.yml

sed -i -e 's/app: percona-deployment/app: percona-deploy-cstor/g' \
-e 's/value: openebs-cstor-csi/value: openebs-cstor-disk/g' \
-e 's/value: app-percona-ns/value: percona-cstor-ns/g' percona_cstor.yml

sed -i '/command:/i \
          - name: RUN_ID\
            value: '"$run_id"'\
' percona_cstor.yml

sed -i '/name: TARGET_AFFINITY_CHECK/{n;s/.*/            value: /g}' percona_cstor.yml

cat percona_cstor.yml

bash ../../openebs-openshift-e2e/script/utils/e2e_job_runner label='app:percona-deploy-cstor' job=percona_cstor.yml
cd ../..

bash openebs-openshift-e2e/script/utils/dump_cluster_state;
bash openebs-openshift-e2e/script/utils/event_updater jobname:percona-cstor $test_name jobid:"$job_id" pipeline_id:"$pipeline_id"

rc_val=$(echo $?)
current_time=$(eval $time)

if [ "$rc_val" != "0" ]; then
bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-cstor jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Fail
exit 1;
fi

bash openebs-openshift-e2e/script/utils/e2e-cr jobname:percona-cstor jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" openebs_version:"$releaseTag" test_result:Pass
if [ "$rc_val" != "0" ]; then
exit 1;
fi

}

if [ "$1" == "node" ];then
  node $2 $3 $4 $5
else
  pod
fi