#!/bin/bash
set -x

pod() {
echo $CI_JOB_ID
###clone e2e-openshift-repo
echo "cloning e2e-openshift repo*************"
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'git clone -b OpenEBS-base https://github.com/openebs/e2e-openshift.git'
sshpass -p $pass ssh -o StrictHostKeyChecking=no $user@$ip -p $port 'cd e2e-openshift && bash Openshift-EE/pipelines/OpenEBS-base/stages/4-chaos/1PP5-app-kill/app-kill node '"'$CI_JOB_ID'"'' '"'$CI_PIPELINE_ID'"'
}

node() {
job_id=$(echo $1)
pipeline_id=$(echo $2)
case_id=1PP5

time="date"
current_time=$(eval $time)

present_dir=$(pwd)
echo $present_dir

bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Waiting
bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Running init_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

echo "*******Deploying Busybox Application****"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-provision-app-kill metadata="")
echo $test_name

cd litmus
echo "Running the litmus test for Busybox Deployment.."

cp apps/busybox/deployers/run_litmus_test.yml busybox_app_kill.yml

sed -i -e 's/app: busybox-litmus/app: deploy-busybox-app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: app-busybox-ns/value: app-kill/g' busybox_app_kill.yml
cat busybox_app_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:deploy-busybox-app-kill' job=busybox_app_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

echo "*******Performing Application POd Chaos**********"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=application-pod-failure metadata="")
echo $test_name

cd litmus
cp apps/jenkins/chaos/app_pod_failure/run_litmus_test.yml appkill.yml

sed -i -e 's/app=jenkins-app/app=app-kill/g' \
-e 's/value: app-jenkins-ns/value: app-kill/g' appkill.yml

echo "Running the litmus test for Busybox Deployment application pod kill.."
cat appkill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='name:application-pod-failure' job=appkill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

if [ "$?" != "0" ]; then
exit 1;
fi

echo "********Deprovisioning Busybox Application*******"

test_name=$(bash Openshift-EE/utils/generate_test_name testcase=busybox-deprovision-app-kill metadata="")
echo $test_name

cd litmus
cp apps/busybox/deployers/run_litmus_test.yml deprovision_app_kill.yml

sed -i -e 's/generateName: litmus-busybox-deploy/generateName: busybox-deprovision-app-kill/g' \
-e 's/app: busybox-litmus/app: busybox-deprovision-app-kill/g' \
-e 's/app=busybox-sts/app=app-kill/g' \
-e 's/value: statefulset/value: deployment/g' \
-e 's/value: openebs-busybox/value: openebs-bb-appkill/g' \
-e 's/value: openebs-cstor-sparse/value: openebs-cstor-disk/g' \
-e 's/value: app-busybox-ns/value: app-kill/g' \
-e 's/value: provision/value: deprovision/g' deprovision_app_kill.yml

echo "Running the litmus test for Busybox Deployment.."
cat deprovision_app_kill.yml

bash ../Openshift-EE/utils/litmus_job_runner label='app:busybox-deprovision-app-kill' job=deprovision_app_kill.yml
cd ..
bash Openshift-EE/utils/dump_cluster_state;
bash Openshift-EE/utils/event_updater jobname:app-kill $test_name jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id"

rc_val=$(echo $?)
test_case_id="1PP5-$pipeline_id"
source ~/.profile
gittoken=$(echo "$github_token")
testResult=$(kubectl get litmusresult ${test_name} --no-headers -o custom-columns=:spec.testStatus.result)
python3 Openshift-EE/utils/result/result_update.py $test_case_id 1PP5 4-chaos "Induce application pod failure and check if it is recovered successfully" $testResult $gittoken

if [ "$rc_val" != "0" ]; then
exit 1;
fi

current_time=$(eval $time)
bash Openshift-EE/utils/e2e-cr jobname:app-kill jobphase:Completed end_time:"$current_time" jobid:"$job_id" pipelineid:"$pipeline_id" testcaseid:"$case_id" test_result:Pass
}

if [ "$1" == "node" ];then
  node $2 $3
else
  pod
fi
